### PR TITLE
fix(icon-button): use onClick instead of onAction to ensure keyboard behaviour is handled by default

### LINKED ISSUE #5791: Escape key does not close modals/ menus when IconButton is focused
### Current behaviour

When the IconButton is focused it stops propagation on any key that is not enter or space 🤦 

Focus IconButton
Press escape
shed a solitary tear as the modal or menu is still open

### Expected behaviour

Escape key works even when IconButton is focused

### CodeSandbox or Storybook URL

https://carbon.sage.com/index.html?path=/story/dialog--default-story

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

Don't stop propagation. Use the exposed interface for `button`, ie. use `onClick` instead of `onAction` as it will mean the keyboard behaviour is handled by default

### Carbon Version

latest

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by tomdavies73**
fix #5791

### Proposed behaviour

A deprecation warning has been added for the use of `onAction` within the `IconButton` component, and `onClick` has been added to replace its functionality, and will ensure keyboard behaviour is handled by default. All instances of `onAction` have been replaced by `onClick` internally also. As `onAction` will soon be removed and `onClick` has been added, an invariant has been added to ensure both cannot be used at the same time, as this would result in potentially incorrect behaviour.

### Current behaviour

Currently, when `IconButton` is focused, it stops propagation on any key that is not enter or space due to `onAction` event being primarily used within `IconButton`.

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.
https://codesandbox.io/s/carbon-quickstart-forked-98jlke?file=/src/App.js

### CODE REVIEW

File: src/components/icon-button/icon-button.component.tsx [hunk 1]
```diff
@@ -21,26 +22,47 @@ export interface IconButtonProps extends SpaceProps {
   /** Callback triggered on mouse leave */
   onMouseLeave?: (ev: React.MouseEvent<HTMLButtonElement>) => void;
   /** Action callback */
```
Comment (Parsium) [inline src/components/icon-button/icon-button.component.tsx:24]:
```suggestion
  /** [DEPRECATED - use `onClick` instead] Action callback */
```
It might be worth additionally amending the prop's description so the deprecation is visible in storybook and via intellisense

File: src/components/icon-button/icon-button.spec.tsx [hunk 2]
```diff
@@ -12,17 +12,79 @@ import StyledIconButton from "./icon-button.style";
...
+      jest.restoreAllMocks();
+    });
+
+    afterEach(() => {
+      loggerSpy.mockRestore();
+    });
+
+    afterAll(() => {
+      loggerSpy.mockClear();
+    });
```
Comment (Parsium) [inline src/components/icon-button/icon-button.spec.tsx:36]: Since there is only one test in this `describe` block, you could probably get away with putting the `loggerSpy` logic inside the test itself to reduce the lines of code. I'm happy to accept otherwise though as this is minor :)

**Review by Parsium — COMMENTED** [review]
Looks good to me @tomdavies73 👍🏼 Just a few minor comments from me. Let me know what you think

File: src/components/icon-button/icon-button.component.tsx [hunk 3]
```diff
@@ -21,26 +22,47 @@ export interface IconButtonProps extends SpaceProps {
...
       children,
       disabled,
       ...rest
     }: IconButtonProps,
     ref
   ) => {
+    if (!onActionButtonWarnTriggered && onAction) {
+      onActionButtonWarnTriggered = true;
+      Logger.deprecate(
+        "The `onAction` callback for the `IconButton` component is deprecated and will soon be removed"
```
Comment (edleeks87) [inline src/components/icon-button/icon-button.component.tsx:57]: Can you add to use onClick here please just so we're explicit etc

File: src/components/icon-button/icon-button.spec.tsx [hunk 4]
```diff
@@ -12,17 +12,67 @@ import StyledIconButton from "./icon-button.style";
...
+jest.mock("../../__internal__/utils/logger");
 
 describe("IconButton component", () => {
   let wrapper: ReactWrapper;
   let onDismiss: jest.Mock;
+  let loggerSpy: jest.SpyInstance<void, [message: string]> | jest.Mock;
+
+  describe("deprecation warning", () => {
+    it("should display deprecation warning when the onAction is passed to the component is used once", () => {
+      loggerSpy = jest.spyOn(Logger, "deprecate");
```
Comment (Parsium) [inline src/components/icon-button/icon-button.spec.tsx:26]:
```suggestion
  describe("deprecation warning", () => {
    it("should display deprecation warning when the onAction is passed to the component is used once", () => {
      const loggerSpy = jest.spyOn(Logger, "deprecate");
```
For readability I would move the scope of `loggerSpy` to inside the test since it is not used elsewhere

File: src/components/icon-button/icon-button.component.tsx [hunk 5]
```diff
@@ -20,27 +21,48 @@ export interface IconButtonProps extends SpaceProps {
...
       children,
       disabled,
       ...rest
     }: IconButtonProps,
     ref
   ) => {
+    if (!onActionButtonWarnTriggered && onAction) {
+      onActionButtonWarnTriggered = true;
+      Logger.deprecate(
+        "The `onAction` callback for the `IconButton` component is deprecated and will soon be removed. Please use onClick instead"
```
Comment (edleeks87) [inline src/components/icon-button/icon-button.component.tsx:57]:
```suggestion
        "The `onAction` callback for the `IconButton` component is deprecated and will soon be removed. Please use `onClick` instead"
```

**Review by Parsium — APPROVED** [review]

**Review by edleeks87 — DISMISSED** [review]

**Comment by ZhuoyuJin** [comment]
There are couple of _component.js_ files which I think need to amend 'onAction' to 'onClick', **dialog.compoent.js**, **link-preview.component.js, menu-full-screen.component.js, sidebar.component.js** and **toast.component.js**. Their corresponding tsx files have been already amended. Please let me know if there's any reason for keeping the 'onAction' in those files. Thanks!

**Review by ZhuoyuJin — COMMENTED** [review]
There are couple of _component.js_ files which I think need to amend 'onAction' to 'onClick', **dialog.compoent.js, link-preview.component.js, menu-full-screen.component.js, sidebar.component.js** and **toast.component.js**. Their corresponding tsx files have been already amended. Please let me know if there's any reason for keeping the 'onAction' in those files. Thanks!

**Review by ZhuoyuJin — APPROVED** [review]

**Review by Parsium — APPROVED** [review]

**Review by ZhuoyuJin — APPROVED** [review]
