### PR TITLE
fix(anchor-navigation): add missing target prop definition

### LINKED ISSUE #3030: AnchorNavigationItem target  props missing
### Current behaviour
image
 target is missing in AnchorNavigationItem => Compilation error

### Expected behaviour
Possibilty to add target prop in AnchorNavigationItem .

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 28.0.0

### PR DESCRIPTION
**Pull request by mkrds**
### Proposed behaviour

This PR adds missing `target` prop definition both to propTypes and type declaration file.

### Current behaviour

Currently `target` prop is not defined which causes compilation errors in typescript projects

### Checklist

<del>- [ ] Screenshots are included in the PR</del>
<del>- [ ] Carbon implementation and Design System documentation are congruent</del>
<del>- [ ] All themes are supported</del>
- [x] Commits follow our style guide
<del>- [ ] Unit tests added or updated</del>
<del>- [ ] Cypress automation tests added or updated</del>
<del>- [ ] Storybook added or updated</del>
- [x] Typescript `d.ts` file added or updated

### Additional context
Closes #3030

### CODE REVIEW

File: src/components/anchor-navigation/anchor-navigation-item.d.ts [hunk 1]
```diff
@@ -14,6 +14,8 @@ export interface AnchorNavigationItemProps {
   isSelected: boolean;
   /** Allows to override existing component styles */
   styleOverride?: () => object | object;
+  /** Reference to the section html element meant to be shown   */
+  target?: HTMLElement;
```
Comment (jamime) [inline src/components/anchor-navigation/anchor-navigation-item.d.ts:18]:
```suggestion
  target?: RefObject<HTMLElement>;
```

Shouldn't this be a `RefObject`?

File: src/components/anchor-navigation/anchor-navigation-item.component.js [hunk 2]
```diff
@@ -33,7 +34,9 @@ AnchorNavigationItem.propTypes = {
   /** Indicates if component is selected */
   isSelected: PropTypes.bool,
   /** Allows to override existing component styles */
-  styleOverride: PropTypes.oneOfType([PropTypes.func, PropTypes.object])
+  styleOverride: PropTypes.oneOfType([PropTypes.func, PropTypes.object]),
+  /** Reference to the section html element meant to be shown   */
+  target: PropTypes.shape({ current: PropTypes.instanceOf(Element) })
```
Comment (jamime) [inline src/components/anchor-navigation/anchor-navigation-item.component.js:39]:
```suggestion
  target: PropTypes.shape({ current: PropTypes.instanceOf(PropTypes.Element) })
```
