### PR TITLE
fix(date, date-range): ensure date format override returns correct formatted value

### LINKED ISSUE #7345: Custom date format is changing date swapping day and month
### Description

Using `DateInput` and `DateRange` with the `dateFormatOverride` prop to customize format I see date is changed. When selecting 12th May 2025 it then changes it to 5th December 2025.

I expect the date not to be changed.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-xe8krcwx?file=src%2FApp.tsx

### Steps to reproduce

_No response_

### JIRA ticket numbers (Sage only)

_No response_

### Suggested solution

_No response_

### Carbon version

153.0.0

### React version

v17

### Design tokens version

_No response_

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Additional context

_No response_

### Confidentiality

- [x] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by nuria1110**
fix #7345

### Proposed behaviour

- Both `dateFormatOverride` prop and translation key can be used, with the prop taking precedence.
- Format override is respected regardles of default locale format. 

https://github.com/user-attachments/assets/a19a265c-11db-49ae-982a-c46c866510e1

### Current behaviour

- `dateFormatOverride` prop has no effect.
- When using the `dateFormatOverride` translation key, it fails to format values correctly and parse correct raw value for the `onChange` event, specially when the day and month are flipped.

Using de-DE locale:

https://github.com/user-attachments/assets/990ef2b9-d929-4408-97bb-4f9c396f10cf

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Playwright automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [x] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

- Can be tested in `i18n Story` test story in storybook and changing the `dateFormatOverride`, see actions for returned formatted and raw values. 
- Separator formatting should also be supported with format override: e.g. `03-06-2019` should update to `03/06/2019` if date format is `dd/MM/yyyy`.

### CODE REVIEW

File: src/components/date/__internal__/date-formats/index.ts
Comment (nuria1110) [inline src/components/date/__internal__/date-formats/index.ts:1]: Looks like James was correct [here](https://github.com/Sage/carbon/pull/7040#discussion_r1824306575) and we should be generating the list of formats to match from the override string and not from the locale format, which is what was causing the mismatch when day and month values were swapped.

File: src/components/date/date-test.stories.tsx [hunk 1]
```diff
@@ -240,12 +266,18 @@ MultipleDates.storyName =
...
 
-export const I18NStory = (args: I18nArgs) => {
+const locales = {
+  "en-US": enUS,
+  "en-GB": enGB,
+  "zh-CN": zhCN,
+  "de-DE": de,
+};
+
+export const I18NStory = ({ locale, ...args }: DateInputI80NProps) => {
```
Comment (Parsium) [inline src/components/date/date-test.stories.tsx:280]: **praise**: nice idea using Storybook Controls to change the locale for testing :+1:

File: src/components/date/__internal__/date-formats/date-formats.test.ts [hunk 2]
```diff
@@ -511,33 +511,59 @@ test("should default to en-GB locale if no locale code string passed to `getForm
...
-
-      expect(
-        expectedFormats.every((formatStr) => formats.includes(formatStr)) &&
-          formats.length === expectedFormats.length,
-      ).toEqual(true);
-
-      expect(format).toEqual(dateFormatOverride);
-    },
-  );
+  test("should return the expected formats when `dateFormatOverride` is passed as NA locale", () => {
```
Comment (edleeks87) [inline src/components/date/__internal__/date-formats/date-formats.test.ts]: suggestion: `test` -> `it` when they're in `describe` blocks

File: src/components/date/date.pw.tsx [hunk 3]
```diff
@@ -868,6 +868,41 @@ test.describe("Functionality tests", () => {
       await page.hover("body"); // hover on body to close the tooltip
     });
   });
+
+  test("should format the date input value according to `dateFormatOverride` prop when using the date-picker", async ({
```
Comment (edleeks87) [inline src/components/date/date.pw.tsx]: comment (non-blocking): I'm not sure we need these to be PW tests as there's nothing browser specific we're relying on etc, not the end of the world having them though

Comment (nuria1110) [reply src/components/date/date.pw.tsx]: Can't remember why I added them in the first place, removed them

**Review by dariusbercea-sage — APPROVED** [review]
