### PR TITLE
fix(button): render falsy children

### LINKED ISSUE #6108: [ Button ] - Children prop evaluate to falsy
### Current behaviour

Given a button component
When the `iconType` prop is not passed
And `children` prop is falsy 
Then the children won't be rendered

### Expected behaviour

Given a button component
When the `iconType` prop is not passed
And `children` prop is falsy 
Then the children is rendered

### CodeSandbox or Storybook URL

https://codesandbox.io/s/prod-glitter-ypps3s?file=/src/App.js

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

119.0.1

### Design Tokens Version

4.19.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by MarcServat**
fix #6108

### Proposed behaviour
The Button will render all falsy values as a children unless `undefined` and `false`

### Current behaviour
The Button treat falsy values as `false`. As a consequence does not render falsy values, like 0, within the `span` and also the component throws an error when the iconType prop is not passed and a falsy value is passed as children. 

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

**Review by Parsium — APPROVED** [review]

**Review by tomdavies73 — APPROVED** [review]

File: src/components/button/button.component.tsx [hunk 1]
```diff
@@ -131,12 +131,14 @@ RenderChildrenProps) {
     bgSize: "extra-small",
   };
 
+  const isValidChildren = children !== undefined && children !== false;
+
   return (
     <>
-      {iconType && iconPosition === "before" && children && (
+      {iconType && iconPosition === "before" && isValidChildren && (
```
Comment (nineteen88) [inline src/components/button/button.component.tsx:138]: suggestion: we could just use Boolean(children) to achieve the same goal

Comment (MarcServat) [reply src/components/button/button.component.tsx:138]: not really, because the `Boolean` will convert to `false` a falsy value resulting in the same behavior as before. e.g.
```Boolean(0) // false```

Comment (nineteen88) [reply src/components/button/button.component.tsx:138]: Yeah fair point and forgot the point of the fix. No worries!

**Review by nineteen88 — APPROVED** [review]

**Review by ZhuoyuJin — APPROVED** [review]
