### PR TITLE
fix(flat-table): sort icon colour fix

### LINKED ISSUE #6523: change colour of sort icon on flat table header
### Desired behaviour

Sufficient colour contrast on sort header icon. 

### Current behaviour

The colour of the sort icon on the flat table, (see docs: https://carbon.sage.com/?path=/docs/flat-table--with-sorting-headers#with-sorting-headers) doesn't meet colour contrast requirements for a11y. 

### Suggested Solution

_No response_

### CodeSandbox or Storybook URL

_No response_

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by nuria1110**
fix #6523

### Proposed behaviour

Updated sort icon colours in FlatTable to have sufficient contrast with the background of FlatTableHeader. 

### Current behaviour

Sort icon colour in FlatTable does not have sufficient contrast with the background of FlatTableHeader. 

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### CODE REVIEW

File: src/components/flat-table/sort/sort.component.tsx [hunk 1]
```diff
@@ -40,9 +42,13 @@ const Sort = ({ children, onClick, sortType }: SortProps) => {
       >
         {children}
         {sortType && (
-          <Icon
+          <StyledSortIcon
             type={sortType === "ascending" ? "sort_up" : "sort_down"}
-            color="--colorsUtilityMajor200"
+            iconColor={
+              colorTheme === "dark"
+                ? "--colorsActionMinorYang100"
```
Comment (Parsium) [inline src/components/flat-table/sort/sort.component.tsx:49]: **issue**: it seems the dark style rule is being overridden by another more specific one:

Screenshot 2024-03-05 at 17 03 08

Looking at the applied CSS rules in the browser console, it appears [this rule within `StyledFlatTableRow`](https://github.com/Sage/carbon/blob/e474046cdf8dec7fea4294b5f7647ed8b3856bdf/src/components/flat-table/flat-table-row/flat-table-row.style.ts#L188-L190) is the culprit:

```css
[data-component="icon"]:not([color]) {
    color: var(--colorsActionMinor500);
}
``` 

One potential way to fix this would be to override the icon colour to be this token within [`StyledCellContent`](StyledCellContent) instead.

**Review by Parsium — COMMENTED** [review]
**issue**: it seems

File: src/components/flat-table/sort/sort.style.ts [hunk 2]
```diff
@@ -45,4 +40,13 @@ const StyledSpaceHolder = styled.div`
   width: 22px;
 `;
 
-export { StyledSort, StyledSpaceHolder };
+interface StylesSortIconProps extends StyledIconProps {
+  iconColor?: string;
+}
+
+const StyledSortIcon = styled(Icon)<StylesSortIconProps>`
+  padding-left: 6px;
```
Comment (DipperTheDan) [inline src/components/flat-table/sort/sort.style.ts:48]: **suggestion(non-blocking):** feel free to leave as is or if you want to use a design token here, the value for 6px is `spacing075`. I'm happy either way though.

**Review by DipperTheDan — DISMISSED** [review]

**Review by Parsium — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by Parsium — APPROVED** [review]

**Review by ZhuoyuJin — APPROVED** [review]
