### PR TITLE
fix(flat-table-row): ensure any cells preceding row headers are also positioned sticky FE-3763

### LINKED ISSUE #3564: FlatTable - Border not correct when using flat table row headers
### Current behaviour

There is a thin border at the header row but a thick border for the rest of the rows in the main body of the table.
 
### Expected behaviour

The border should be a consistent thick border to show that the first column is a column of row headers. 

### Reproducible example

See https://carbon.sage.com/?path=/story/design-system-flat-table--with-row-header with-row-header story of the flat table
image

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 55.0.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | Chrome
| npm              | 
| Operating System | Mac OS Catalina

### LINKED ISSUE #3716: FlatTable - focus line is thinner when flatTable has vertical split line
### Current behaviour

Focus line in first colum is tinner
### Expected behaviour

Focus line has the same thickness for both columns in flatTable
### Reproducible example

1. Open https://carbon.sage.com/?path=/story/design-system-flat-table--highlightable-rows
2. Click on the row
3. Focus line is tinner 
flatTable

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 66.4.0
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | all
| npm              |
| Operating System | Win10

### LINKED ISSUE #3721: Checkboxes do not work along side row headers
### Current behaviour

When using FlatTableCheckbox alongside FlatTableRowHeader when you scroll to the right the row header remains where it is but the checkbox scrolls off the screen. 

### Expected behaviour

The checkbox should remain next to the row header and the rest of the content should scroll behind it, like it does with the row header

### Reproducible example

I added Row headers to the MDX example in storybook

### PR DESCRIPTION
**Pull request by edleeks87**
fix #3721
fix #3716
fix #3564

### Proposed behaviour

Any `FlatTableCell`, `FlatTableCheckbox` or `FlatTableHeader` children that precede a
`FlatTableRowHeader` will also be positioned `sticky`. They will also be passed a callback to
`reportCellWidth` which will allow each column to calculate the correct `left` positioning based on
the sum of the offsetWidths of the columns before it

Fixes focus styling of `FlatTableRowHeader` when a row has focus

Adds `border-left` to the cell directly after a `FlatTableRowHeader` to fix style defect, passes
context from `FlatTable` to `FlatTablerow` to ensure that the border has the correct colour defined
by `colorTheme` prop

### Current behaviour

Any preceding columns are not made sticky when a `FlatTableRowHeader` is used
Styling is wrong when is incorrect when row has focus a `FlatTableRowHeader` is used

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Additional context

image

image

### Testing instructions

will add a codesandbox to demonstrate focus style updates

`design-system-flat-table--with-row-header` has been refactored to demonstrate the fix to sticky columns

### CODE REVIEW

File: src/components/flat-table/flat-table-row/flat-table-row.component.js [hunk 1]
```diff
@@ -112,6 +154,10 @@ const FlatTableRow = React.forwardRef(
                     firstColumnExpandable
                       ? handleCellKeyDown
                       : undefined,
+                  cellIndex: index,
+                  reportCellWidth:
+                    index < rowHeaderIndex ? reportCellWidth : undefined,
```
Comment (dawidzarzycki) [inline src/components/flat-table/flat-table-row/flat-table-row.component.js:159]: I think that we can as well

```suggestion
                    index < rowHeaderIndex && reportCellWidth
```

File: src/components/flat-table/flat-table-row/flat-table-row.spec.js [hunk 2]
```diff
@@ -15,6 +15,9 @@ import StyledFlatTableCheckbox from "../flat-table-checkbox/flat-table-checkbox.
 import { SidebarContext } from "../../drawer";
 import FlatTableCheckbox from "../flat-table-checkbox";
 import StyledIcon from "../../icon/icon.style";
+import FlatTableRowHeader from "../flat-table-row-header/flat-table-row-header.component";
+import FlatTableHeader from "../flat-table-header/flat-table-header.component";
```
Comment (dawidzarzycki) [inline src/components/flat-table/flat-table-row/flat-table-row.spec.js:19]: I guess that we can import all components from one source as
```js
import { FlatTableRowHeader, FlatTableHeader, ...<more components> from '../flat-table' }
```

File: src/components/flat-table/flat-table-row/flat-table-row.style.js [hunk 3]
```diff
@@ -6,6 +6,45 @@ import StyledFlatTableCheckbox from "../flat-table-checkbox/flat-table-checkbox.
 import StyledFlatTableHeader from "../flat-table-header/flat-table-header.style";
 import StyledIcon from "../../icon/icon.style";
 
+const stickyColumnFocusStyling = (index, theme) => {
+  return `
+    border-bottom: 1px solid transparent;
+    ${index === 0 ? `border-left: 1px solid ${theme.colors.focus};` : ""}
```
Comment (dawidzarzycki) [inline src/components/flat-table/flat-table-row/flat-table-row.style.js:12]:
```suggestion
    ${index === 0 && `border-left: 1px solid ${theme.colors.focus};`}
```

File: src/components/flat-table/flat-table-row/flat-table-row.component.js [hunk 4]
```diff
@@ -25,12 +33,31 @@ const FlatTableRow = React.forwardRef(
...
+    );
+    const colorTheme = useContext(FlatTableThemeContext);
+
+    const reportCellWidth = useCallback(
+      (width, index) => {
+        const copiedArray = stickyCellWidths;
+        if (copiedArray[index] !== undefined) {
+          copiedArray[index] = width;
+        } else {
+          copiedArray.push(width);
```
[the remark this answers is not in the document]
Comment (edleeks87) [reply src/components/flat-table/flat-table-row/flat-table-row.component.js:50]: To add it to the array of widths that are then set into state

File: src/components/flat-table/flat-table-row/flat-table-row.component.js [hunk 5]
```diff
@@ -25,12 +33,31 @@ const FlatTableRow = React.forwardRef(
...
+    const childrenArray = React.Children.toArray(children);
+    const rowHeaderIndex = childrenArray.findIndex(
+      (child) => child.type === FlatTableRowHeader
+    );
+    const colorTheme = useContext(FlatTableThemeContext);
+
+    const reportCellWidth = useCallback(
+      (width, index) => {
+        const copiedArray = stickyCellWidths;
+        if (copiedArray[index] !== undefined) {
```
[the remark this answers is not in the document]
Comment (edleeks87) [reply src/components/flat-table/flat-table-row/flat-table-row.component.js:47]: 0 also counts as falsy so this needs to be `copiedArray[index] !== undefined`

File: src/components/flat-table/flat-table-row/flat-table-row.component.js (hunk 1 above)
Comment (edleeks87) [reply src/components/flat-table/flat-table-row/flat-table-row.component.js:159]: I think this would actually pass a `boolean` to the prop rather than a `function/ undefined`

File: src/components/flat-table/flat-table-row/flat-table-row.spec.js (hunk 2 above)
Comment (edleeks87) [reply src/components/flat-table/flat-table-row/flat-table-row.spec.js:19]: I'm not sure it makes a huge difference in a spec file as it's not bundled etc

File: src/components/flat-table/flat-table-row/flat-table-row.style.js [hunk 6]
```diff
@@ -6,6 +6,45 @@ import StyledFlatTableCheckbox from "../flat-table-checkbox/flat-table-checkbox.
...
+    background-clip: padding-box;
+    z-index: ${theme.zIndex.overlay};
```
Comment (sjohnson-sage) [inline src/components/flat-table/flat-table-row/flat-table-row.style.js:14]: Why does it need a z-index?

File: src/components/flat-table/flat-table-row/flat-table-row.style.js [hunk 7]
```diff
@@ -6,6 +6,45 @@ import StyledFlatTableCheckbox from "../flat-table-checkbox/flat-table-checkbox.
...
+      content: "";
+      border-top: 2px solid ${theme.colors.focus};
+      border-bottom: 1px solid ${theme.colors.focus};
+      display: block;
+      left: 0px;
+      top: -1px;
+      height: 99%;
+      width: 101%;
+      position: absolute;
+      z-index: ${theme.zIndex.overlay};
```
Comment (sjohnson-sage) [inline src/components/flat-table/flat-table-row/flat-table-row.style.js:26]: Same question here

**Review by sjohnson-sage — COMMENTED** [review]
Just a few comments, and I'm not totally convinced adding all this complexity for these bugs is a good idea, but I can't think of a better way to do it so it'll have to do!

File: src/components/flat-table/flat-table-row/flat-table-row.style.js (hunk 6 above)
Comment (edleeks87) [reply src/components/flat-table/flat-table-row/flat-table-row.style.js:14]: Honestly not sure, it was existing code that I moved as I needed to define it for any other columns that were before the sticky header. I'll have a little dig around and see if it's needed

File: src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js [hunk 8]
```diff
@@ -14,10 +14,15 @@ const FlatTableRowHeader = ({
   expandable = false,
   onClick,
   onKeyDown,
+  leftPosition,
   ...rest
 }) => {
+  const ref = useRef(null);
```
[the remark this answers is not in the document]
Comment (edleeks87) [reply src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js:20]: Yep forgot to remove 👍

File: src/components/flat-table/flat-table-row/flat-table-row.component.js [hunk 9]
```diff
@@ -25,12 +33,31 @@ const FlatTableRow = React.forwardRef(
     const [isExpanded, setIsExpanded] = useState(expanded);
     const rowRef = ref || useRef();
     const firstColumnExpandable = expandableArea === "firstColumn";
+    const [stickyCellWidths, setStickyCellWidths] = useState([]);
+    const [leftPositions, setLeftPositions] = useState([]);
+    const childrenArray = React.Children.toArray(children);
+    const rowHeaderIndex = childrenArray.findIndex(
+      (child) => child.type === FlatTableRowHeader
```
[the remark this answers is not in the document]
Comment (edleeks87) [reply src/components/flat-table/flat-table-row/flat-table-row.component.js:40]: Ah good shout, I'll add a test and update if needed

File: src/components/flat-table/flat-table-row/flat-table-row.style.js (hunk 6 above)
Comment (edleeks87) [reply src/components/flat-table/flat-table-row/flat-table-row.style.js:14]: @dawidzarzycki  it looks like you added the z-index here, do you know why it was done? Whilst I can't see what impact removing them will have I'm a little hesitant to do it in case it effects something I'm not aware of

File: src/components/flat-table/flat-table-row/flat-table-row.style.js (hunk 7 above)
Comment (edleeks87) [reply src/components/flat-table/flat-table-row/flat-table-row.style.js:26]: see above

File: src/components/flat-table/flat-table-row/flat-table-row.spec.js (hunk 2 above)
Comment (dawidzarzycki) [reply src/components/flat-table/flat-table-row/flat-table-row.spec.js:19]: oh right it is spec file :)

File: src/components/flat-table/flat-table-row/flat-table-row.style.js (hunk 6 above)
Comment (dawidzarzycki) [reply src/components/flat-table/flat-table-row/flat-table-row.style.js:14]: If I'm not wrong I just changed hardcoded zIndex into one that comes from theme object

Comment (edleeks87) [reply src/components/flat-table/flat-table-row/flat-table-row.style.js:14]: @sjohnson-sage looks like it's needed to ensure the focus outline isn't hidden behind the sticky columns

image

Comment (grabkowski) [reply src/components/flat-table/flat-table-row/flat-table-row.style.js:14]: looks like we need it for the row header focus overlay

File: src/components/flat-table/flat-table-row/flat-table-row.component.js (hunk 1 above)
Comment (dawidzarzycki) [reply src/components/flat-table/flat-table-row/flat-table-row.component.js]: It will/should pass the function anyway

Comment (edleeks87) [reply src/components/flat-table/flat-table-row/flat-table-row.component.js]: It passes a boolean with your suggestion if the first condition fails, I need it to either pass a function or undefined. If you update the code to your suggestion you get a prop type warning

image

**Review by sjohnson-sage — APPROVED** [review]

**Review by dawidzarzycki — DISMISSED** [review]

**Review by sjohnson-sage — APPROVED** [review]

**Review by dawidzarzycki — DISMISSED** [review]

**Review by sjohnson-sage — DISMISSED** [review]

**Review by dawidzarzycki — APPROVED** [review]

**Review by DlgSHi — APPROVED** [review]
