### PR TITLE
fix(scroll-block): fix page scrolling - FE-5041

### LINKED ISSUE #4969: Select - opening dropdown scrolls entire page to the top
### Current behaviour

See codesandbox below. Scroll down the page and open the select dropdown - the entire page scrolls to the top. 

### Expected behaviour

The page should not scroll up, or down, when you open a select dropdown.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/nervous-surf-q1owig?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-30380

### Suggested Solution

This bug was introduced in [104.14.0](https://github.com/Sage/carbon/compare/v104.13.0...v104.14.0)

After investigating with @mkrds - we believe that the scroll blocking values added to the html tag (documentElement)[here](https://github.com/Sage/carbon/blob/master/src/hooks/__internal__/useScrollBlock/useScrollBlock.js#L24) are the cause of this issue.

We also believe that they aren't necessary and can be removed, although we need to do this in a way that won't break backwards compatibility with the `ScrollBlockManager` for MFEs.

### Carbon Version

104.14.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by mkrds**
### Proposed behaviour

Fixes #4969 

This PR fixes an issue where any component that uses `useScrollBlock` hook util causes the screen scroll to jump to the top when there is a `height: 100vh` set on the `body` element. 
This PR also refactors slightly the `useScrollBlock` hook so that it will be more futureproof and flexible in the future.

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

To test the issue described in the FE-5041 ticket:
https://codesandbox.io/s/carbon-quickstart-forked-jfe3o5?file=/src/index.js

To test compatibility with previous versions of carbon locally:
1. Clone https://github.com/jamime/multiple-carbon-versions repo
2. Checkout branch `FE-5041`
3. Run `npm install` and then `npm start`
4. Go to http://localhost:3000
5. Test different scenarios

### CODE REVIEW

**Review by samtjo — APPROVED** [review]

File: src/hooks/__internal__/useScrollBlock/useScrollBlock.js [hunk 1]
```diff
@@ -59,18 +69,31 @@ const useScrollBlock = () => {
       ({ element, property }) => element.style[property]
     );
 
+    originalValuesRef.current = originalValues;
+    scrollBlockManager.saveRestoreValuesCallback(restoreValues);
+    // TODO: saveOriginalValues can be removed
     scrollBlockManager.saveOriginalValues(originalValues);
-
-    rules.forEach(({ element, property, blockingValue }) => {
+    // TODO: slice san be removed
```
Comment (samtjo) [inline src/hooks/__internal__/useScrollBlock/useScrollBlock.js:76]:
```suggestion
    // TODO: slice can be removed
```

Comment (samtjo) [reply src/hooks/__internal__/useScrollBlock/useScrollBlock.js:76]: Not blocking the PR for this though 😅

**Review by jamime — APPROVED** [review]

**Review by divyajindel — APPROVED** [review]
