### PR TITLE
fix(character-counter): fixed character counter inconsistencies

### LINKED ISSUE #7825: [Text Editor - Accessibility Issue - Voiceover] - Character Count Error
### Description

I am using the Carbon Text Editor component.
When using VoiceOver with Safari, the character count is being read out incorrectly.
I understand with VoiceOver, it can often repeat the values however when VoiceOver reads out the character count for the second time, often these values are read out differently.
It also feels like the character count value can often become out of sync slightly with user interactions (after adding/deleting text in the input field)
E.g. 
3000 characters remaining
0 characters remaining 

Can be seen in the Carbon storybook examples: https://carbon.sage.com/?path=/story/text-editor--demo

https://github.com/user-attachments/assets/4fdb7c63-6981-40ef-81ff-ebaae0165d5b

I would expect the same number character count be read out to users, not for it to change.

### Reproduction

https://carbon.sage.com/?path=/story/text-editor--demo

### Steps to reproduce

Open this story: https://carbon.sage.com/?path=/story/text-editor--demo
Use VoiceOver with safari
Observe the VoiceOver character count for the text editor input field.

### JIRA ticket numbers (Sage only)

SBS-156556

### Suggested solution

_No response_

### Carbon version

158.35.5

### React version

v17

### Design tokens version

4.35.0

### Relevant browsers

Safari

### Relevant OSs

MacOS

### Assistive technologies

Using Voice Over with Safari - Safari Version 26.2 (21623.1.14.11.9)

### Additional context

_No response_

### Confidentiality

- [x] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by mihai-albu-sage**
fixes: #7825

### Proposed behaviour

Two changes were introduced to the `CharacterCounter` plugin:
- The initial value was updated from 0 to `maxChars` to ensure it is announced correctly by VoiceOver when the component first loads.
- The visual character counter was removed from the accessibility tree using `aria-hidden="true"`, so it is only announced once.

### Current behaviour
- When the text editor component loads for the first time, if we are navigating while the VoiceOver is on, the character count is announced as zero when focusing the visually hidden character counter using the keyboard navigation.
- While navigating with VoiceOver enabled, the character count is announced twice, as focus moves first to the visible character counter and then to the hidden one.

### Checklist

- [X] Commits follow our style guide
- [X] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [X] Unit tests added or updated if required
- [ ] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

- Open the storybook and go to the Text Editor demo page
- Open VoiceOver
- Navigate using the Control + Arrows keys

### CODE REVIEW

**Review by DipperTheDan — DISMISSED** [review]

File: src/components/text-editor/__internal__/__ui__/CharacterCounter/character-counter.component.tsx [hunk 1]
```diff
@@ -70,12 +70,14 @@ const CharacterCounterPlugin = ({
...
         data-role={`${namespace}-character-limit`}
         marginTop={marginTop ?? "var(--spacing050)"}
+        aria-hidden="true"
       >
         {locale.textEditor.characterCounter(
           getFormatNumber(rawCharactersRemaining),
         )}
       </StyledCharacterCounter>
       <VisuallyHiddenCharacterCounter
+        data-role={`${namespace}-live-character-counter`}
```
Comment (tomdavies73) [inline src/components/text-editor/__internal__/__ui__/CharacterCounter/character-counter.component.tsx]: **suggestion**: I think this data-role should also include the fact that this count is hidden. Something like:

`namespace-hidden-live-character-counter` etc. 👍

**Review by tomdavies73 — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by paulrobinson88 — APPROVED** [review]
