### PR TITLE
fix(reponsive-vertical-menu-item): item rendering and onClick behaviour consistency

### LINKED ISSUE #7575: ResponsiveVerticalMenuItem doesn't handle pressing Enter/Space
### Description

ResponsiveVerticalMenuItem doesn't handle pressing the Enter/Space keys.

### Reproduction

https://stackblitz.com/edit/carbon-demo-github-issue-7574?file=src%2FApp.tsx

### Steps to reproduce

1. Open the menu
2. Press the Enter or Space key
3. See that nothing happens

### JIRA ticket numbers (Sage only)

SBS-145102

### Suggested solution

_No response_

### Carbon version

157.1.1

### React version

v17

### Design tokens version

_No response_

### Relevant browsers

Chrome

### Relevant OSs

Windows

### Additional context

We want ResponsiveVerticalMenuItem  to open a dialog, when we press Enter/Space.

### Confidentiality

- [x] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by tomdavies73**
fix #7575

### Proposed behaviour

when the responsive vertical menu item is rendered as an anchor element, the onClick behaviour is now consistently aligned with native HTML behaviour. The responsive vertical menu item now also supports being rendered as a button if no `href` is passed and an onClick is passed. This means the onClick can be triggered on space & enter key press and on a click event for specific use cases

### Current behaviour

Currently, onClick is not properly aligned with HTML behaviour when the responsive vertical menu item is rendered as a link and is only triggered on click. Also there is no option to render the responsive vertical menu item as a button to support onClick being called in more cases, which is not consistent with our approach in other menu-based components.

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

Pass `onClick` to any test story, as needed. Pass a href and/or an onClick to render an `a` on click should only be fired on click or enter key when focused. When an onClick is passed with no href this will render a `button`, on click should only be fired on click or enter/space key when focused.

Side note: onClick will only be triggered on the last available item, e.g. last nested item or an item with no nested menu children.

### CODE REVIEW

File: src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.component.tsx [hunk 1]
```diff
@@ -42,8 +47,9 @@ interface BaseItemProps extends MarginProps, PaddingProps {
   /** The label for the menu item. */
   label: React.ReactNode;
   /** A custom click handler to run when an anchor link is clicked */
-  onClick?: (event: React.MouseEvent<HTMLAnchorElement>) => void;
-  /** The rel attribute to be used for the underlying <a> tag */
+  onClick?: (
+    event: ResponsiveVerticalMenuItemClickEvent,
+  ) => void /** The rel attribute to be used for the underlying <a> tag */;
```
Comment (DipperTheDan) [inline src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.component.tsx]: **nitpick(non-blocking):** Formatting is somehow borked here.

```suggestion
  onClick?: (
    event: ResponsiveVerticalMenuItemClickEvent,
  ) => void 
  /** The rel attribute to be used for the underlying <a> tag */;
```

**Review by paulrobinson88 — APPROVED** [review]
