### PR TITLE
fix(switch): fix alignment issue with component when no new validation is applied

### LINKED ISSUE #6303: Padding bottom not good in switch component
### Current behaviour

The Padding bottom is not good in the switch component between the label and the input. 
There is no issue if validationRedesignOptIn is not defined in CarbonProvider. 
We don't have this issue in carbon version 118.4.0 .

### Expected behaviour

We should have the same behaviour as described in the https://carbon.sage.com/?path=/docs/switch--default  

### CodeSandbox or Storybook URL

https://codesandbox.io/s/dry-pine-krlgp9?file=/src/index.js:381-404

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

Latest

### Design Tokens Version

120.1.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by DipperTheDan**
A bug is present whereby when the new validation style is used and no hint text or validation message is passed to the component, the label appears to be misaligned

fixes #6303

### Proposed behaviour

Screenshot 2023-11-01 at 13 32 14

### Current behaviour

Screenshot 2023-09-23 at 18 14 34

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Playwright automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

N/A

### Testing instructions

There should be no other styling regressions to Switch in the new or old style validations.

### CODE REVIEW

File: src/components/switch/switch.component.tsx [hunk 1]
```diff
@@ -214,16 +214,23 @@ export const Switch = React.forwardRef(
...
+
     return (
       <>
         {validationRedesignOptIn ? (
           <StyledSwitch {...switchStylePropsForNewValidation}>
             <Label>
-              {label}
-              {labelHelp && <StyledHintText>{labelHelp}</StyledHintText>}
+              <Box
+                ml={applyValidation ? "0px" : "2px"}
```
Comment (edleeks87) [inline src/components/switch/switch.component.tsx:225]: comment: the ticket talks about using the correct design token so it might be better to do something like below

```
 ml={applyValidation ? 0 : "2px"}
 mb={labelHelp ? 0 : 1}

Comment (edleeks87) [reply src/components/switch/switch.component.tsx:225]: I also wonder if we need the left margin at all (maybe missed something there)

File: src/components/switch/switch.component.tsx [hunk 2]
```diff
@@ -214,16 +214,23 @@ export const Switch = React.forwardRef(
...
+                mb={labelHelp ? "0px" : "8px"}
+              >
+                {label}
+                {labelHelp && <StyledHintText>{labelHelp}</StyledHintText>}
+              </Box>
               <Box position="relative">
                 <ValidationMessage error={error} warning={warning} />
-                {(error || warning) && (
+                {applyValidation && (
                   <ErrorBorder warning={!!(!error && warning)} />
```
Comment (edleeks87) [inline src/components/switch/switch.component.tsx:234]: comment: I realise this isn't part of this PR but there's no need to coerce here it's already a boolean and I can't un-see it

```suggestion
                  <ErrorBorder warning={!error && warning} />
```

Comment (DipperTheDan) [reply src/components/switch/switch.component.tsx:234]: Yeah, I remember seeing this originally and wondered why it was done this was. I just followed the pattern that was already in place originally. I'll happily get this changed though 😆

Comment (DipperTheDan) [reply src/components/switch/switch.component.tsx:231]: Haven't made this change as per our private conversation btw.

Comment (edleeks87) [reply src/components/switch/switch.component.tsx:231]: No worries, looks like TS can't infer the type correctly here nvm

**Review by edleeks87 — APPROVED** [review]

**Review by Parsium — APPROVED** [review]

**Review by stephenogorman — APPROVED** [review]
