### PR TITLE
fix(dialog): add accessibility props for modal based components (FE-4469)

### LINKED ISSUE #4537: Accessibility props for DialogFullScreen component
### Desired behaviour

Allow `role` and `aria-labelledby` props to be passed to the DialogFullScreenComponent:
```
<body>
  <nav>Nav content goes here</nav>
    <DialogFullScreen data-role="dialog-full-screen" role="main" aria-labelledby="heading-1">
      <h1 id="heading-1">Dialog Heading</h1>
      <p>Dialog paragraph</p>
    </DialogFullScreen>
</body>
```
Expected be rendered as follows in the browser:
```
<body>
  <nav>Nav content goes here</nav>
  <span portal-id="abcd"/>
  <div portal-id="abcd">
    <div data-role="dialog-full-screen" role="main" aria-labelledby="heading-1">
      <h1 id="heading-1">Dialog Heading</h1>
      <p>Dialog paragraph</p>
  </div>
  </div>
</body>
```

### Current behaviour

When using the DialogFullScreen component which uses React Portals, this renders the dialog outside the normal DOM hierarchy where the below code:
```
<body>
  <nav>Nav content goes here</nav>
  <main>
    <DialogFullScreen data-role="dialog-full-screen">
      <h1>Dialog Heading</h1>
      <p>Dialog paragraph</p>
    </DialogFullScreen>
  </main>
</body>
```
Can be viewed as follows in the browser:
```
<body>
  <nav>Nav content goes here</nav>
  <main>
    <span portal-id="abcd"/>
  </main>
  <div portal-id="abcd">. <---- div is outside main landmark
    <div data-role="dialog-full-screen">
      <h1>Dialog Heading</h1>
      <p>Dialog paragraph</p>
  </div>
  </div>
</body>
```

### Suggested Solution

Allow `role` and `aria-labelledby` props to be passed to the same div which has `data-component` and `data-role` prop values in the DialogFullScreen component. This enables all children elements within the DialogFullScreen component to be enclosed within a landmark for accessibility.

See accessibility rule link for more information: https://dequeuniversity.com/rules/axe/4.3/region?application=AxeChrome

### CodeSandbox or Storybook URL

N/A

### Anything else we should know?

N/A

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### LINKED ISSUE #4687: FullScreenDialog ARIA-MODAL implementation for screen voice command tools
### Desired behaviour

When using screen voice command tools and asking for the numbers on the screen to show, the dialog should only show current active/opened modal numbers and not the ones that could exist behind.

### Current behaviour

When opening a modal, fullscreen mode and asking the voice command tool e.g Mac OS VoiceOver to show the numbers to navigate using voice commands it shows the focusable elements and links form active modal and behind elements which is not correct based on a11y preferences

### Suggested Solution

add aria-modal and role dialog to the StyledFullScreenDialog to cater for this a11y issue

### CodeSandbox or Storybook URL

https://carbon.sage.com/storybook?path=/docs/dialog-full-screen--default-story

### Anything else we should know?

Current scope SBS-25895

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by grabkowski**
### Proposed behaviour

Add missing ARIA props to:
- Dialog,
- DialogFullscreen,
- Alert,
- Confirm,
- Sidebar,
- AdvancedColorPicker

### Current behaviour

ARIA props not passed down to HTML in Modal based components

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

Closes #4537
Closes #4687

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

**Review by DipperTheDan — DISMISSED** [review]

**Review by mkrds — DISMISSED** [review]

File: src/components/dialog-full-screen/dialog-full-screen.d.ts [hunk 1]
```diff
@@ -16,8 +39,10 @@ export interface DialogFullScreenProps extends ModalProps {
   subtitle?: string;
   /** Title displayed at top of dialog */
   title?: React.ReactNode;
+  /** The ARIA role to be applied to the DialogFulscreen container */
+  role?: string;
 }
 
-declare class DialogFullScreen extends Modal<DialogFullScreenProps> {}
+declare function DialogFullScreen(props: DialogFullScreenProps): JSX.Element;
```
Comment (DipperTheDan) [inline src/components/dialog-full-screen/dialog-full-screen.d.ts:46]: This line here should fix this open issue. https://github.com/Sage/carbon/issues/4669
Would you be able to add a `fixes` or `closes` message to the commit so we can get this issue closed at the same time please?

**Review by DipperTheDan — APPROVED** [review]

File: src/components/dialog-full-screen/dialog-full-screen.d.ts (hunk 1 above)
Comment (grabkowski) [reply src/components/dialog-full-screen/dialog-full-screen.d.ts:46]: I wasn't aware of this issue, it's now linked in the commit message

**Review by DipperTheDan — APPROVED** [review]

**Review by mkrds — APPROVED** [review]

**Review by divyajindel — APPROVED** [review]
