### PR TITLE
fix: remove unused variants from Toast and Message components - FE-4234

### LINKED ISSUE #4248: Toast variant prop options don't work
### Current behaviour
A few of the options for the `Toast` `variant` prop do not work, `maintenance` for example (see sandbox). The docs also don't give the list of options for this prop: 

image

### Expected behaviour
The docs should show the correct list of options and they should all work.

### Reproducible example
https://codesandbox.io/s/prod-moon-26jzm?file=/src/index.js

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | Latest
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          |
| npm              |
| Operating System |

### PR DESCRIPTION
**Pull request by mkrds**
### Proposed behaviour

Fixes #4248 

Removes `maintenance`, `help`, `new` and `default` prop options of `variant` from both Toast and Message components

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

Check Toast and Message stories and prop tables

### CODE REVIEW

**Review by edleeks87 — APPROVED** [review]

File: src/components/toast/toast.d.ts [hunk 1]
```diff
@@ -4,25 +4,9 @@ export interface ToastPropTypes {
...
-  variant?:
-    | "default"
-    | "error"
-    | "help"
-    | "info"
-    | "maintenance"
-    | "new"
-    | "success"
-    | "warning";
+  variant?: "error" | "info" | "success" | "warning";
```
Comment (samtjo) [inline src/components/toast/toast.d.ts:7]: Let's tidy this up a bit with a `type ToastVariants = "error" | "info" | "success" | "warning";` which can be shared on both these props here

**Review by edleeks87 — DISMISSED** [review]

**Review by samtjo — APPROVED** [review]

**Review by jamime — CHANGES_REQUESTED** [review]

**Review by jamime — APPROVED** [review]

**Review by samtjo — DISMISSED** [review]

**Review by samtjo — APPROVED** [review]

**Review by DlgSHi — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]
