### PR TITLE
fix(select): reposition the select list after select has changed position - FE-5303

### LINKED ISSUE #5351: Select is not center well if render changed after open dropdown
### Current behaviour

When i open my select, if dropdown is displayed and something appears after, my component is not align well if i want my components aligned.

### Expected behaviour

I should not have difference when i display something after my dropdown is opened.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/confident-shape-448hys?file=/src/index.js

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

109.5.2

### Design Tokens Version

_No response_

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### LINKED ISSUE #5465: Select options render outside of active Dialog component
### Current behaviour

I recently upgraded to 110.2.4 from 106.6.6 and now all of the Select components we've got nested in Dialogs drop their options list to the bottom of the dialog. 

### Expected behaviour

The options list renders in the expected area (i.e. relative to the dropdown's location)

### CodeSandbox or Storybook URL

https://codesandbox.io/s/carbon-quickstart-forked-mru1ih?file=/src/index.js

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

110.2.4

### Design Tokens Version

2.30.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by mkrds**
### Proposed behaviour

FE-5303 FE-5365 FE-5371 FE-5314

Fixes #5351 
Fixes #5465

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Testing instructions

Apart from testing the issues linked in PR I'd also suggest testing positioning mechanisms for all components using our internal `Popover` component:

ActionPopover
Date
DateRange
MultiActionButton
SplitButton
all Select components

This PR also fixes an issue where scroll blocking for Select components stopped working, to test it use this story -
https://carbon.sage.com/?path=/story/form--in-dialog-with-sticky-footer
It should not be possible to scroll the dialog content when Select component is open.

### CODE REVIEW

**Comment by edleeks87** [comment]
There's seems to still be an issue in both the demo added to storybook and the sandbox below

image

https://codesandbox.io/s/carbon-quickstart-forked-7gxcpd

**Review by edleeks87 — COMMENTED** [review]
There's seems to still be an issue in both the demo added to storybook and the sandbox below

image

https://codesandbox.io/s/carbon-quickstart-forked-7gxcpd

**Review by edleeks87 — APPROVED** [review]

File: src/components/select/filterable-select/filterable-select.component.js [hunk 1]
```diff
@@ -596,9 +596,6 @@ FilterableSelect.propTypes = {
   listMaxHeight: PropTypes.number,
   /** Placement of the select list in relation to the input element */
   listPlacement: PropTypes.oneOf([
-    "auto",
-    "auto-start",
-    "auto-end",
     "top",
     "top-start",
     "top-end",
```
Comment (robinzigmond) [inline src/components/select/filterable-select/filterable-select.component.js:601]: so if floatingUi no longer has these "auto" placement options and we take them in as a prop, I guess this becomes a breaking change, as anyone using one of them will now get a TS/PropTypes error and it will do nothing anyway.

**Review by robinzigmond — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by DlgSHi — APPROVED** [review]

**Review by robinzigmond — APPROVED** [review]
