### PR TITLE
fix(date): prevent calling onChange when input is blurred and value has not changed FE-5161

### LINKED ISSUE #5120: [Date] the onChange event is triggered after blur calling on component
### Current behaviour

1. `git checkout master` & `npm ci` & `npm start`
2. Open [storybook](https://carbon.sage.com/?path=/docs/date-input-test--default-story) 
3. Press `Tab` twice to focus and then blur the component
4. onChange event is called

### Expected behaviour

the onChange event should be called only after real change of the value of the input

### CodeSandbox or Storybook URL

https://carbon.sbc-ui.com/?path=/story/date-input-test--default-story

### JIRA Ticket (Sage Only)

FE-5161

### Suggested Solution

_No response_

### Carbon Version

106.1.5

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by edleeks87**
fix #5120

### Proposed behaviour

Prevents `onChange` from being called when input is blurred and the value has not updated

### Current behaviour

When the initial value is different from the given locale's format it will call onChange when the input is blurred

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Unit tests added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

Compare the the story in linked issue with local version

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

File: src/components/date/__internal__/utils.js [hunk 1]
```diff
@@ -103,7 +103,7 @@ function findMatchWithNoSeparators(valueString, formatString) {
   const valueArray = makeSeparatedValues(indexArray, valueString);
 
   if (checkForCompleteMatch(formatArray, valueArray)) {
-    return [formatArray.join("."), valueArray.join(".")];
+    return [formatArray.join(" "), valueArray.join(" ")];
```
Comment (edleeks87) [inline src/components/date/__internal__/utils.js:106]: this was changed to prevent clashes with locales that use `.` as a separator, as the guard added to `onBlur` would not work for them

**Review by DipperTheDan — DISMISSED** [review]

**Review by mkrds — DISMISSED** [review]

**Review by DipperTheDan — APPROVED** [review]
