### PR TITLE
fix(decimal): ensure that value prop is reliably displayed - FE-5153

### LINKED ISSUE #5103: Decimal: doesn't reliably display its props.value
### Current behaviour

If onchange handler changes the value passed back to the control, it seems to ignore it.

Typically we will truncate the number of characters after the decimal point, any subsequent characters being suppressed.
This used to work on Carbon 95.1, but not on 106.0
In Sandbox: I've mimicked behaviour: 
Type 22.22222 into the decimal. We are overriding value to remain at 22.22, but control displays the longer string, and stays that way when tabbing out.
On Carbon 95.1, it seems to toggle between 22.22 and 22.222, but would always revert to 22.22 on tabbing out.

But not an issue when setting value programmatically. 
Clicking button on sandbox does work.

### Expected behaviour

The decimal control would display the value being passed into its props.value

### CodeSandbox or Storybook URL

https://codesandbox.io/s/pensive-easley-tz9lsf

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

106.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by DipperTheDan**
The decimal component should reliably show the correct value when the component is controlled. Due
to how the controlled functionality is managed internally, ensuring that `stateValue` is included
the `useEffect` that manages the controlled value is enough to ensure this happens.

fixes #5103

### Proposed behaviour

- Decimal component should be reliably displaying its `value` prop.

decimal_value_reliable

### Current behaviour
 
- In certain conditions, Decimal component is not reliably displaying its `value` prop.

decimal_value_not_reliable

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

N/A

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

Codesandbox to test this PR is this one: [modest-dust-omhv0j](https://codesandbox.io/s/modest-dust-omhv0j)

### CODE REVIEW

File: src/components/decimal/decimal.component.js [hunk 1]
```diff
@@ -227,17 +227,24 @@ const Decimal = ({
...
+        setStateValue(formatValue(valueProp));
+
+        if (valueProp === "" && prevValue === "") {
+          setStateValue(formatValue(emptyValue));
+        }
       }
     }
     // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, [value]);
+  }, [value, componentShouldUpdate]);
```
Comment (edleeks87) [inline src/components/decimal/decimal.component.js:247]: I think we should remove the disable lint and add all the dependencies here, or at least replace `componentShouldUpdate` with `stateValue`

```
  }, [value, stateValue, emptyValue, formatValue, getSafeValueProp, isControlled, prevValue, toStandardDecimal]);
```

File: src/components/decimal/decimal.component.js [hunk 2]
```diff
@@ -227,17 +227,24 @@ const Decimal = ({
...
+  const componentShouldUpdate = stateValue === value;
+
   useEffect(() => {
     const unformattedValue = toStandardDecimal(stateValue);
 
     if (isControlled) {
       const valueProp = getSafeValueProp(value);
       if (unformattedValue !== valueProp) {
-        setStateValue(formatValue(value));
+        setStateValue(formatValue(valueProp));
```
Comment (edleeks87) [inline src/components/decimal/decimal.component.js:239]:
```suggestion
      if (valueProp === "" && prevValue === "") {
          setStateValue(formatValue(emptyValue));
        } else {
          setStateValue(formatValue(valueProp));
        }
```

So we're not potentially setting state twice 👍

File: src/components/decimal/decimal.component.js [hunk 3]
```diff
@@ -227,17 +227,24 @@ const Decimal = ({
     prevControlledRef.current = isControlled;
   }, [isControlled]);
 
+  const prevValue = usePrevious(value);
+  const componentShouldUpdate = stateValue === value;
+
   useEffect(() => {
     const unformattedValue = toStandardDecimal(stateValue);
```
Comment (edleeks87) [inline src/components/decimal/decimal.component.js:234]: IMHO the naming here could be a little clearer, as we discussed on slack something like `standardDecimalValue` might be more intuitive but I'm also okay with you keeping it as is if you disagree

File: src/components/decimal/decimal.component.js (hunk 1 above)
Comment (edleeks87) [reply src/components/decimal/decimal.component.js:247]: It will likely lead to the test breaking that we discussed on slack, lets catch up tomorrow and we can look at updating it as I'm not convinced it's testing controlled behaviour like we want

**Review by edleeks87 — APPROVED** [review]

File: src/components/decimal/decimal-test.stories.mdx [hunk 4]
```diff
@@ -119,6 +119,29 @@ export const NewValidationStory = (args) => {
...
+  const [state, setState] = useState("0.01");
+  const handleChange = (e) => {
+    let newValue = e.target.value.rawValue;
+    if (newValue.startsWith("22.22")) newValue = "22.22";
+    action("onChange")(e, newValue);
+    setState(newValue);
+  };
+  return (
+    <div>
+      If you try and type "22.222", the onChange should block the last "2" from being entered and you should see "22.22" in the textbox.
```
[the remark this answers is not in the document]
Comment (DipperTheDan) [reply src/components/decimal/decimal-test.stories.mdx:132]: Good spot. I'll get this amended 👍🏻

**Review by robinzigmond — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]
