### PR TITLE
fix(validations): fix various accessibility issues (FE-5382, FE-5337)

### LINKED ISSUE #5411: Textbox - Validation icon uses invalid ARIA attribues
### Current behaviour

When using Textbox validation (and presumably others), the validation icon is presented as a span with an `aria-label` attribute set, but no valid role attribute.

This has been detected when running the Axe Dev Tools to check for accessibility requirements and can be recreated in Storybook on the latest Carbon version (see below)

Screenshot 2022-08-24 at 12 28 56

### Expected behaviour

A valid role is applied to the span in question. No error appears when scanning using Axe Dev Tools.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/textbox--validations-string-component

### JIRA Ticket (Sage Only)

SKPU-7210

### Suggested Solution

_No response_

### Carbon Version

110.1.1

### Design Tokens Version

_No response_

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS, Windows

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### LINKED ISSUE #5498: Resolve accessibility violation for validation icon
### Current behaviour

Axe reports accessibility issue for validation icon in Textbox component.

**Issue Description:** Ensures ARIA attributes are allowed for an element's role
**Fix the following:** aria-label attribute cannot be used on a span with no valid role attribute.

#### Axe Report Screenshot
image

### Expected behaviour

Axe does not report accessibility issues for validation icon.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/validation-icon-accessibility-m4fu34

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

109.1.2

### Design Tokens Version

2.40.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### LINKED ISSUE #5594: 'Elements must only use allowed ARIA attributes' with labelHelp errors.
### Current behaviour

Business DD > Manage Users > Add user > click 'Add' > 2 labelHelp appear > run axe report.
Axe report returns 'Elements must only use allowed ARIA attributes'
"To solve this problem, you need to...
aria-label attribute cannot be used on a span with no valid role attribute."

### Expected behaviour

No results on the axe report.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/textbox--validations-string-label

### JIRA Ticket (Sage Only)

SBS-45292

### Suggested Solution

Axe report links to this URL https://dequeuniversity.com/rules/axe/4.4/aria-allowed-attr?application=AxeChrome

### Carbon Version

111.0.0

### Design Tokens Version

2.42.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### LINKED ISSUE #5828: Error unannounced in forms
### Current behaviour

Error message is not read by VoiceOver when they appear

### Expected behaviour

Error message is read by VoiceOver when they appear

### CodeSandbox or Storybook URL

https://codesandbox.io/s/admiring-dust-jnecnj

### JIRA Ticket (Sage Only)

SBS-48611, SBS-48601

### Suggested Solution

_No response_

### Carbon Version

114.9.1

### Design Tokens Version

_No response_

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by grabkowski**
Validation icon was labelled by the aria-label attribute, which was not compliant with WCAG standards and resulted in accessibility issues.
Added `aria-describedby` attribute, that points to the tooltip content.
Added id to the validation message to be used in `aria-describedby` on the input.
 
### Proposed behaviour

Resolve accessibility errors on validation icon.
Enable error announcement on redesigned validations.

### Current behaviour

Accessibility issues on validation icon, when rendered in the textField and on the label.
Errors not announced on redesigned validations.

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
~~- [ ] Screenshots are included in the PR if useful~~
~~- [ ] All themes are supported if required~~
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
~~- [ ] Storybook added or updated if required~~
~~- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required~~
~~- [ ] Typescript `d.ts` file added or updated if required~~
~~- [ ] Related docs have been updated if required~~

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

fixes #5411
fixes #5498
fixes #5594
fixes #5828

### Testing instructions

There is no test for the tooltip content. Previous test just checked the aria-label attribute which should not be placed on an element that triggers a tooltip.

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

File: src/__internal__/checkable-input/checkable-input.component.tsx [hunk 1]
```diff
@@ -133,7 +133,7 @@ const CheckableInput = React.forwardRef(
       name: id,
       reverse,
       warning,
-      validationIconId,
+      validationId,
```
Comment (Parsium) [inline src/__internal__/checkable-input/checkable-input.component.tsx:136]: I don't think this would be recognised by `FormField` as it would expect a `validationIconId` prop instead. What do you think about doing this? 

```suggestion
      validationIconId: validationId,
```

File: src/components/checkbox/checkbox.test.js [hunk 2]
```diff
@@ -238,27 +238,21 @@ context("Testing Checkbox component", () => {
   it("should render Checkbox component with error message", () => {
     CypressMountWithProviders(<CheckboxComponent error="Error has occurred" />);
 
-    checkboxIcon()
-      .should("have.attr", "aria-label", "Error has occurred")
-      .should("have.attr", "data-element", "error");
+    checkboxIcon().should("have.attr", "data-element", "error");
```
Comment (Parsium) [inline src/components/checkbox/checkbox.test.js:241]: Personally I think we still need to verify if the tooltip message has been rendered alongside checking the icon. What do you think about adding the following assertion so we are testing if the icon and tooltip are both rendered? This would also apply to the two succeeding tests as well :) 

```suggestion
    checkboxIcon().should("have.attr", "data-element", "error");
    tooltipPreview().should("have.text", "Error has occurred");
```

File: src/components/checkbox/checkbox.test.js [hunk 3]
```diff
@@ -415,29 +409,23 @@ context("Testing Checkbox component", () => {
           <CheckboxGroupComponent error="Error has occurred" />
         );
 
-        checkboxGroupIcon()
-          .should("have.attr", "aria-label", "Error has occurred")
-          .should("have.attr", "data-element", "error");
+        checkboxGroupIcon().should("have.attr", "data-element", "error");
```
Comment (Parsium) [inline src/components/checkbox/checkbox.test.js:412]: Similar to the single checkbox tests

```suggestion
        checkboxGroupIcon().should("have.attr", "data-element", "error");
        tooltipPreview().should("have.text", "Error has occurred");
```

File: src/components/radio-button/radiobutton.test.js [hunk 4]
```diff
@@ -316,29 +298,23 @@ context("Testing RadioButton component", () => {
       <RadiobuttonComponent error="Error has occurred" />
     );
 
-    radiobuttonIcon()
-      .should("have.attr", "aria-label", "Error has occurred")
-      .should("have.attr", "data-element", "error");
+    radiobuttonIcon().should("have.attr", "data-element", "error");
```
Comment (Parsium) [inline src/components/radio-button/radiobutton.test.js:301]: Similar to Checkbox for the changed tests in this file

```suggestion
    radiobuttonIcon().should("have.attr", "data-element", "error");
    tooltipPreview().should("have.text", "Error has occurred");
```

File: src/__internal__/checkable-input/checkable-input.component.tsx (hunk 1 above)
Comment (grabkowski) [reply src/__internal__/checkable-input/checkable-input.component.tsx]: nice catch, looks like TypeScript compiler did not catch it.
I have fixed that and added a type to that object, so it will not happen in the future. Looks like there was an unnecessary `name` prop that I also removed.

File: src/components/checkbox/checkbox.test.js (hunk 2 above)
Comment (grabkowski) [reply src/components/checkbox/checkbox.test.js:241]: this was not testing that the tooltip was rendered, this was just checking if the aria-label attribute is on the icon, which should not be added here, so I decided to remove it completely. As for the tooltip message, I'll leave it to QA, as this should be added later by them if necessary:
image

File: src/__internal__/validation-message/validation-message.component.tsx [hunk 5]
```diff
@@ -5,17 +5,26 @@ export interface ValidationMessageProps {
   /** Indicate that error has occurred
   Pass string to display hint with error */
   error?: boolean | string;
+  /** Id of the  component, to be used for accessibility purposes */
```
Comment (DipperTheDan) [inline src/__internal__/validation-message/validation-message.component.tsx:8]:
```suggestion
  /** Id of the component, to be used for accessibility purposes */
```

File: src/components/checkbox/checkbox.test.js (hunk 2 above)
Comment (DipperTheDan) [reply src/components/checkbox/checkbox.test.js:241]: We'll need to make sure that the person QA'ing this definitely does add the needed Cypress tests.

**Review by Parsium — DISMISSED** [review]

**Review by DipperTheDan — APPROVED** [review]

File: src/components/checkbox/checkbox.test.js (hunk 2 above)
Comment (DlgSHi) [reply src/components/checkbox/checkbox.test.js:241]: I don't agree with adding additional tests because we:
1. already have tests for tooltip for each component 
2. need to unskip all tests with `validation`

Comment (Parsium) [reply src/components/checkbox/checkbox.test.js:241]: Good point @DlgSHi 👍🏼

In that case what do you think @grabkowski of amending the test descriptions to something like "should render Checkbox component with error icon" - since we aren't asserting if the message has been rendered but the icon. Happy to accept if otherwise as this is minor

File: src/components/date-range/date-range.test.js [hunk 6]
```diff
@@ -506,204 +506,193 @@ context("Test for DateRange component", () => {
...
-        "should check accessibility with the tooltipPosition is set to %s",
-        (position) => {
-          CypressMountWithProviders(
-            <DateRangeCustom
-              m={9}
-              tooltipPosition={position}
-              startError={testCypressText}
-            />
-          );
+    it.each([["top"], ["bottom"], ["left"], ["right"]])(
```
Comment (Parsium) [inline src/components/date-range/date-range.test.js:606]: This can also be written as this :)
```suggestion
    it.each(["top", "bottom", "left", "right"])(
```

Comment (grabkowski) [reply src/components/date-range/date-range.test.js]: changed

File: src/components/checkbox/checkbox.test.js (hunk 2 above)
Comment (grabkowski) [reply src/components/checkbox/checkbox.test.js:241]: changed

File: src/__internal__/checkable-input/checkable-input.component.tsx
Comment (Parsium) [inline src/__internal__/checkable-input/checkable-input.component.tsx:1]: I noticed we are passing `aria-labelledby` to `HiddenCheckableInput` but the code of `HiddenCheckableInput` uses `ariaLabelledBy` instead. It seems given the component's type interface:

```ts
export interface CommonHiddenCheckableInputProps
  extends Omit<
    React.InputHTMLAttributes<HTMLInputElement>, // extended interface includes `aria-labelledby` and `aria-describedby`
    "value" | "size" | "type"
  > {
  ariaDescribedBy?: string;
  ariaLabelledBy?: string;
  // more props...
}
```

that the component accepts kebab-case and non kebab-case version of the `aria-describedby` and `aria-labelledby` props. This may cause unexpected behaviour since the kebab case props aren't used in the code, so would you be able to modify this? What do you think about using the kebab case version of the props for consistency?

File: src/__internal__/input/input.component.tsx
Comment (Parsium) [inline src/__internal__/input/input.component.tsx:1]: Similarly here because `Input` can accept the kebab-case and non kebab-cases versions of `aria-describedby` and `aria-labelledby` (but only use the non kebab prop) this could cause unexpected behaviour. Would you be able to omit the extended props and use the kebab-case versions of the props?

File: src/hooks/__internal__/useInputAccessibility/useInputAccessibility.ts [hunk 7]
```diff
@@ -1,40 +1,47 @@
...
   warning?: string | boolean;
   info?: string | boolean;
   label?: React.ReactNode;
   fieldHelp?: React.ReactNode;
 }): {
   labelId?: string;
-  validationIconId?: string;
+  validationId?: string;
   fieldHelpId?: string;
   ariaDescribedBy?: string;
```
Comment (Parsium) [inline src/hooks/__internal__/useInputAccessibility/useInputAccessibility.ts:21]: What do you think about doing this so we don't encounter any unexpected behaviour related to prop names?

```suggestion
  "aria-describedby"?: string;
```

File: src/__internal__/checkable-input/checkable-input.component.tsx
Comment (DipperTheDan) [reply src/__internal__/checkable-input/checkable-input.component.tsx:1]: I'm all for keeping things consistent across our components. Good thinking 👍🏻

**Review by DipperTheDan — COMMENTED** [review]
Nothing more to add than what @Parsium has already mentioned.

File: src/__internal__/checkable-input/checkable-input.component.tsx
Comment (grabkowski) [reply src/__internal__/checkable-input/checkable-input.component.tsx:1]: this is an internal component, so there is no reason to pass these props as kebab-case and then converting them again to camelCase multiple times. We do already have `ariaLabelledBy` passed down as camelCase in `CheckableInput`.
When extending all HTML attributes we are just confusing users, as a few props we are overwriting internally, like `aria-describedby`, `aria-checked` or `aria-invalid`, and in my opinion we should not extend that in the first place.

File: src/__internal__/input/input.component.tsx
Comment (grabkowski) [reply src/__internal__/input/input.component.tsx:1]: if I change that , users will still see unexpected behaviour as we are overwriting HTML attributes that are extended in the Input interface. I think that the best way would be to not extend that, or omit these ARIA properties in the interface. In my opinion we should change the other props to camelCase in our internal components to avoid that assignment: `"aria-<prop>": aria<Prop>`

File: src/hooks/__internal__/useInputAccessibility/useInputAccessibility.ts (hunk 7 above)
Comment (grabkowski) [reply src/hooks/__internal__/useInputAccessibility/useInputAccessibility.ts:21]: I think that it would lead to more confusion, as we would have to convert that prop to camelCase when we want to use or modify it.

**Review by Parsium — DISMISSED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]
