### PR TITLE
fix(date): enable width customization (FE-5659)

### LINKED ISSUE #5787: Adapt DateInput to available space
### Desired behaviour

I would like that DateInput component width was adapted to available width, in the same way that other components like Textbox

### Current behaviour

Currently this component has got a fixed width

### Suggested Solution

_No response_

### CodeSandbox or Storybook URL

https://codesandbox.io/s/festive-allen-h9sm9w?file=/src/index.js

### Anything else we should know?

This is the design from UX that we would like to achieve
datetimeforcarbon

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by grabkowski**
### Proposed behaviour

allow the use of labelWidth, inputWidth and MaxWidth props

### Current behaviour

labelWidth, inputWidth and MaxWidth props are ignored, width of the component is non-changeable

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
~~- [ ] Screenshots are included in the PR if useful~~
~~- [ ] All themes are supported if required~~
- [x] Unit tests added or updated if required
~~- [ ] Cypress automation tests added or updated if required~~
- [x] Storybook added or updated if required
~~- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required~~
~~- [ ] Typescript `d.ts` file added or updated if required~~
~~- [ ] Related docs have been updated if required~~

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [x] Carbon implementation matches Design System/designs
- [x] UI Tests GitHub check reviewed if required

### Additional context

fixes #5787

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

File: src/components/date/date.component.js [hunk 1]
```diff
@@ -65,6 +65,9 @@ const DateInput = React.forwardRef(
       tooltipPosition,
       value,
       inputRef,
+      inputWidth,
+      labelWidth,
+      maxWidth,
```
Comment (Parsium) [inline src/components/date/date.component.js:70]: Currently the `maxWidth` prop is not documented in storybook because we have defined the `Textbox`-based props manually in the `stories.mdx` file.

**Review by Parsium — COMMENTED** [review]
Appreciate this isn't part of this PR, but what do you think about disabling the eslint rule on the affected lines for `MockComponent` in the spec file to get rid of those lint warnings?

**Review by edleeks87 — COMMENTED** [review]
Nothing else from me that @Parsium  hasn't already raised

File: src/components/date/date.component.js (hunk 1 above)
Comment (grabkowski) [reply src/components/date/date.component.js:70]: looks like this prop was excluded in our story, should be fixed now.

**Review by Parsium — DISMISSED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by Parsium — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]
