### PR TITLE
fix(select): remove list action button from scrollable area in select list

### LINKED ISSUE #6541: `FilterableSelect` with Action Button: list scrollbar extends beyond list viewport, covers action button
### Current behaviour

When optional Action Button is present, set by the `listActionButton` prop, the scrollbar of the options list extends to the bottom of the menu, which:

- exceeds height of options list viewport
- covers / is over the action button

screenshot_20240124_09 23 00

### Expected behaviour

Extents of scrollbar track should match the height of the options list viewport for which it is scrolling.
The bottom of the scrollbar should therefore end at the top of the action button.

### Storybook URL

https://carbon.sage.com/?path=/docs/select-filterable--default

### CodeSandbox URL

https://codesandbox.io/p/sandbox/ecstatic-dew-t5ldc5?file=%2Fsrc%2FApp.js%3A38%2C24

### JIRA Ticket (Sage Only)

SBS-80319

### Suggested Solution

NOTES: 
- Carbon, SD, and UX teams all agree on the expected behaviour
- Figma assets for this component have the correct version

### Carbon Version

125.3.0

### Design Tokens Version

_No response_

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by edleeks87**
fix #6541

### Proposed behaviour

Adds a new scrollable container to the select list so that the list action button is no longer within the scrollable area.

image

### Current behaviour

List action button is included within the scrollable area in select list

image

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] Unit tests added or updated if required
- [x] Playwright automation tests added or updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### CODE REVIEW

**Review by DipperTheDan — APPROVED** [review]

File: src/__spec_helper__/mock-dom-rect.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
+const getDOMRect = (width: number, height: number) => ({
```
Comment (Parsium) [inline src/__spec_helper__/mock-dom-rect.ts:1]: **suggestion(non-blocking)**: what do you think about adding a return type here?

```suggestion
const getDOMRect = (width: number, height: number): DOMRect => ({
```

**Review by Parsium — DISMISSED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by Parsium — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by sianford — APPROVED** [review]
