### PR TITLE
fix(popover-container): ensure that tab sequence is not lost when container has radio buttons

### LINKED ISSUE #7067: The TAB key sequense is lose when it is used in a Popover component with Radio buttons child
### Description

When I move using the TAB key into a Popover component the navigation jump to the View site information of the browser (side to the URL)

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-igqxxt?file=src%2FApp.tsx

### Steps to reproduce

Press `TAB` key until `With Radio children` button
Press `ENTER`
Press `TAB` key until the last element of the list
Press `TAB` key

### JIRA ticket numbers (Sage only)

SBS-113991

### Suggested solution

_No response_

### Carbon version

142.13.5

### Design tokens version

_No response_

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Additional context

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by DipperTheDan**
This fix ensures that if the last focusable element in a popover container is a radio button, that the tab sequence is not affected once focus is outside of the container

fixes #7067

### Proposed behaviour

https://github.com/user-attachments/assets/5343bd1b-345a-4576-95b1-3df40374833a

### Current behaviour

https://github.com/user-attachments/assets/7e741308-4f29-4d7e-96ae-984f19b466ff

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Playwright automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

N/A

### Testing instructions

**Steps to reproduce**
Using the new `With Radio Button` example:
- Press TAB key until you reach the `with Radio children` button.
- Press ENTER to open the popover container.
- Press TAB key until the last element of the list.
- Press TAB key.
- Focus should move to button next to the popover container's opening button.

There should also be no functional regressions or changes to the other `PopoverContainer` examples.

### CODE REVIEW

**Comment by damienrobson-sage** [comment]
Looks like you can't get off the popover at all when using the `shouldCoverButton` prop (although it can still be closed as normal). 
https://github.com/user-attachments/assets/ad134f7d-eec7-4a7e-bec0-63a2f1c006be

File: src/__internal__/focus-trap/focus-trap.component.tsx [hunk 1]
```diff
@@ -279,7 +279,7 @@ const FocusTrap = ({
     onFocus: updateCurrentFocusedElement,
   });
 
-  // passes focusProps, sets tabIndex and onBlur if no tabIndex has been expicitly set on child
+  // passes focusProps, sets tabIndex and onBlur if no tabIndex has been explicitly set on child
```
Comment (nineteen88) [inline src/__internal__/focus-trap/focus-trap.component.tsx:282]: question: since this isn't related to the commit should we separate it out as it's own chore commit?

**Review by nineteen88 — APPROVED** [review]

File: src/__internal__/focus-trap/focus-trap.component.tsx (hunk 1 above)
Comment (DipperTheDan) [reply src/__internal__/focus-trap/focus-trap.component.tsx:282]: Yeah, good idea. I'll do that when I come to rebase with master, prior to merging the work.

**Review by damienrobson-sage — APPROVED** [review]

**Review by sianford — APPROVED** [review]
