### PR TITLE
fix(dialog): add DialogSizes type to component interface (FE-5390)

### LINKED ISSUE #5516: DialogSizes no longer exported
### Current behaviour

Previously: DialogSizes was accessible by MFEs to import and use as a type.
in v111.0.0 this is no longer the case

### Expected behaviour

DialogSizes capable of being imported as a type into consuming code

### CodeSandbox or Storybook URL

n/a

### JIRA Ticket (Sage Only)

SBS-43091

### Suggested Solution

node_modules/carbon-react/lib/components/dialog/dialog.component.d.ts

```Typescript
- declare type DialogSizes = "auto" | "extra-small" | "small" | "medium-small" | "medium" | "medium-large" | "large" | "extra-large";
+ export declare type DialogSizes = "auto" | "extra-small" | "small" | "medium-small" | "medium" | "medium-large" | "large" | "extra-large";
```

### Carbon Version

v111.0.0

### Design Tokens Version

_No response_

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by Parsium**
closes #5516 

### Proposed behaviour

- Add missing `DialogSizes` type from the interface for the `Dialog` component
- Amend typing of `DialogSizes` so consumers can see their types as literal unions, not type alias names
- Convert story setup to CSF stories with MDX docs approach to allow for story type checking

### Current behaviour

- `DialogSizes` type is missing from `Dialog` interface
- The type of `size` prop of `Dialog` shows as `DialogSizes` and not `extra-small | small | ...`   
- Cannot type check stories

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

- Using the provided codesandboxes, verify the following error has been resolved: ``Module '"carbon-react/lib/components/dialog"' has no exported member 'DialogSizes'.``
- In storybook:
     
     - Verify in `Dialog` prop table that the `size` prop has its possible values documented (i.e. `extra-small`, `small`, etc.) 
     - Verify all `Dialog` stories have their source code correctly rendered under `Show code` and is inline with master.

### CODE REVIEW

**Review by mkrds — DISMISSED** [review]

File: .storybook/isChromatic.d.ts [hunk 1]
```diff
@@ -0,0 +1,2 @@
+declare function isChromatic(): boolean;
```
Comment (robinzigmond) [inline .storybook/isChromatic.d.ts:1]: would it not have been better to convert our `isChromatic.js` to a `.ts` equivalent rather than making a separate `.d.ts` file?

Comment (Parsium) [reply .storybook/isChromatic.d.ts:1]: Our current typescript setup would not allow this unfortunately since we are only compiling `.ts` files only within `src/`. I believe we tried to amend this before but encountered further issues, so I think we should have a dedicated investigation task for this

Comment (robinzigmond) [reply .storybook/isChromatic.d.ts:1]: ah OK fair enough - if it's been tried and doesn't work, then happy for an investigation task to be raised and to use the .d.ts as a workaround.

**Review by robinzigmond — APPROVED** [review]

**Review by mkrds — DISMISSED** [review]

File: .storybook/isChromatic.d.ts (hunk 1 above)
Comment (Parsium) [reply .storybook/isChromatic.d.ts:1]: Raised task as FE-5398

**Comment by Parsium** [comment]
**For QA:** Please use these codesandboxes when testing if `DialogSizes` has been exported:

**Review by divyajindel — APPROVED** [review]

**Review by robinzigmond — DISMISSED** [review]

**Review by robinzigmond — APPROVED** [review]

**Review by mkrds — DISMISSED** [review]

**Review by divyajindel — DISMISSED** [review]

**Review by mkrds — APPROVED** [review]

**Review by robinzigmond — APPROVED** [review]
