### PR TITLE
fix(help): icon tooltip voice reader issue (FE-979)

### LINKED ISSUE #4634: Accessibility violations on Link component - Ensures every ARIA tooltip node has an accessible name
### Current behaviour

In Link component, story `with-Tooltip` has violation "Ensures every ARIA tooltip had an accessible name. 

### Expected behaviour

No accessibility violations. 

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/link--with-tooltip

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### LINKED ISSUE #4676: Textarea - Accessibility Violation with labelHelp
### Current behaviour

ARIA hidden element must not contain focusable elements

### Expected behaviour

There are no accessibility violations.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/textarea--with-label-help

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### LINKED ISSUE #4734: Link with Icon: Add aria-hidden="true" to span wrapping icon
### Current behaviour

Presently the span element that wraps the icon within a Link is considered as the first character of the Link text preventing the Voice Control tool on Mac to recognise the Link text when scanning the page for the phrase spoken by the user.

### Expected behaviour

When the user speaks the Link text phrase, it should be recognised on the page so the user can use voice commands to click the Link.

### CodeSandbox or Storybook URL

N/A

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

Adding aria-hidden="true" to the `<span>` element that wraps the icon within a Link will ensure the Voice Control tool or any other assistive technology does not consider the icon to be part of the Link's text while scanning the page for the phrase spoken by the user and so the user is able to click Link using the Voice Control tool.

### Carbon Version

102.7.3

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by grabkowski**
### Proposed behaviour
Resolve ARIA issues so the component is read correctly in voice readers:
- allow to pass aria-hidden attribute to the Icon HTML
- remove tooltip role from Help and Icon, that role should be set only on the tooltip itself
- add button role to Help
- add aria-describedby attribute to Help so it could reference the tooltip

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

fixes #4676
fixes #4634
fixes #4734

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

File: src/components/help/help.component.js [hunk 1]
```diff
@@ -80,13 +83,14 @@ const Help = ({
             rel: "noopener noreferrer",
           }
         : {
-            role: "tooltip",
+            role: "button",
```
Comment (DipperTheDan) [inline src/components/help/help.component.js:86]: Should this be a `button`? A screen reader will read out that the element is clickable that's all. On a Mac it'll read out something like `You are currently on a button, To click this button press control-option-space` when Help is focused.

**Comment by edleeks87** [comment]
Nothing to add past what Dan has asked

File: src/components/help/help.component.js (hunk 1 above)
Comment (grabkowski) [reply src/components/help/help.component.js:86]: yes, this definitely should be a button, otherwise it will state it is a group. Tooltip role was added incorrectly, as it should be set on a popup.

Comment (DipperTheDan) [reply src/components/help/help.component.js:86]: That's fine. If that is what it is meant to be, I'm good with that 😄

**Review by DipperTheDan — DISMISSED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by DipperTheDan — DISMISSED** [review]

**Review by edleeks87 — DISMISSED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Comment by tempertemper** [comment]
A solid improvement on the tooltip component. I'm still not a huge proponent of tooltips in general (in fact, I'm not a proponent of any kind 😄) but this makes them more accessible to screen reader users. Nice work.

**Review by edleeks87 — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by samtjo — APPROVED** [review]

**Review by sianford — DISMISSED** [review]
Tested in VoiceOver in Safari in macOS, NVDA in Chrome, Firefox and Edge in Windows 10. Repeated failing Firefox cases in VoiceOver on macOS. Where tooltips are not read out by NVDA in Firefox, these are limitations of NVDA's operation in Firefox in Windows and not an issue with the icon tooltips in the Carbon components themselves. Testing passed ✅

**Review by samtjo — APPROVED** [review]

**Review by sianford — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]
