### PR TITLE
fix(flat-table): prevent sorting indicators from impacting text wrapping

### LINKED ISSUE #7586: [FlatTable] Sort header placeholder impacts wrapping when not shown
### Description

When using a sortable FlatTable with long header texts, the wrapping behaves oddly as screen size is reduced.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-vjwnakan?file=src%2FApp.tsx

### Steps to reproduce

1. Open SB demo
2. Resize render pane until wrapping occurs

### JIRA ticket numbers (Sage only)

_No response_

### Suggested solution

The `sort-placeholder` element is causing extra spacing to be added to the header which impacts wrapping. If no sort icon is shown, we should consider whether it's needed at all (it's currently fixed to `inline-block`, but if it **must** remain in the DOM then maybe switching between that and `none` would be better).

### Carbon version

157.4.0

### React version

v18

### Design tokens version

4.35.0

### Relevant browsers

Chrome, Firefox

### Relevant OSs

MacOS

### Assistive technologies

_No response_

### Additional context

_No response_

### Confidentiality

- [x] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by damienrobson-sage**
fixes #7586 

### Proposed behaviour

Use the correct semantic element for the sorting buttons, and ensure that the table headers respect the spacing appropriately

### Current behaviour

When using a sortable FlatTable with long header texts, the wrapping behaves oddly as screen size is reduced. The current implementation of `Sort` in `FlatTable` is also built using a clickable `div` as opposed to a button.

### Checklist

- [x] Commits follow our style guide
- [ ] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

A test story has been added under `FlatTable`: `Extended Column Sorting` which can be used to test the changes.

### CODE REVIEW

File: playwright/components/flat-table/index.ts [hunk 1]
```diff
@@ -74,7 +74,11 @@ export const flatTableCurrentPageInput = (page: Page) =>
 export const flatTableRowHeader = (page: Page) =>
   page.locator(FLAT_TABLE_STICKY_ROW);
 export const flatTableHeaderCellsIcon = (page: Page) =>
-  flatTableHeader(page).locator("th > div > div").locator("span");
+  flatTableHeader(page).locator("th > div > div > span[data-component='icon']");
+export const flatTableHeaderCellsButtonIcon = (page: Page) =>
+  flatTableHeader(page).locator(
+    "th > div > button > span[data-component='icon']",
+  );
```
Comment (nuria1110) [inline playwright/components/flat-table/index.ts]: **suggestion:** Could we locate these elements by targeting them using `data-element` or `data-role` instead? This can easily break if the component structure changes and will also help with clarity on what component is being located.

File: src/components/flat-table/flat-table-test.stories.tsx [hunk 2]
```diff
@@ -1239,3 +1226,146 @@ export const WithLongRowHeader = () => {
...
+export const ExtendedColumnSorting = (args: FlatTableProps) => {
+  const initialHeaders = [
+    { name: "client", label: "Client", isActive: true },
+    { name: "region", label: "Region", isActive: false },
+    { name: "total", label: "Total (£)", isActive: false },
+    { name: "orders", label: "Orders", isActive: false },
+    { name: "lastPurchase", label: "Last Purchase", isActive: false },
+  ];
+
+  const data: TableRowData[] = useMemo(() => {
```
Comment (Parsium) [inline src/components/flat-table/flat-table-test.stories.tsx:1242]: **question(non-blocking)**: does this need to be memoised? I'm guessing it's because the component renders it, which is needed for it to appear in the code snippet. Typically though, I'd expect consumers wouldn't define initial data like this. 

```
  const data: TableRowData[] = useMemo(() => {
```

File: src/components/flat-table/sort/sort.style.ts [hunk 3]
```diff
@@ -1,43 +1,64 @@
...
 
-const StyledSortIcon = styled(Icon)<StylesSortIconProps>`
-  padding-left: var(--spacing075);
-  color: ${({ iconColor }) => `var(${iconColor})`};
+    span[data-component="icon"] {
+      color: ${colorTheme === "dark"
+        ? "var(--colorsActionMinorYang100)"
+        : "var(--colorActionMinor500)"};
+      margin-bottom: 1px;
+    }
```
Comment (Parsium) [inline src/components/flat-table/sort/sort.style.ts:68]: **suggestion**: what do you think of defining these styles within `Icon`? This help ensure `Icon` has full control over its own styling.

`Icon`'s `className` prop could help us achieve this:

```
// icon.style.ts
cosnt StyledIcon = styled.span`
  .flat-table--sort-icon {
      color: ${colorTheme === "dark"
        ? "var(--colorsActionMinorYang100)"
        : "var(--colorActionMinor500)"};
      margin-bottom: 1px;
  }
`

// sort.component.tsx
const icon = () =>
    sortType ? (
    <Icon className="flat-table--sort-icon" type={sortType === "ascending" ? "sort_up" : "sort_down"} />
  ) : (
    <span data-role="sort-placeholder" />
  );
```

File: src/components/flat-table/flat-table-test.stories.tsx (hunk 2 above)
Comment (damienrobson-sage) [reply src/components/flat-table/flat-table-test.stories.tsx:1242]: Correct, it doesn't need to be memoised, this is all just because of how the story is being set up, etc. Customers wouldn't need to rely on this approach.

File: src/components/flat-table/sort/sort.style.ts (hunk 3 above)
Comment (damienrobson-sage) [reply src/components/flat-table/sort/sort.style.ts:68]: I get where you're coming from but I'd rather keep the change focused within `Sort` so that I don't need to start making changes to Icon that would see extra props being added to it and whatnot; `Icon` has no concept of `colorTheme`, for example, so I'd need to add that in, and then add tests for coverage, etc. and the whole ticket's scope inflates beyond what it needs to be.

Comment (Parsium) [reply src/components/flat-table/sort/sort.style.ts:68]: No worries - happy to defer this for now, given it's a small change.

In the near future, it'd be good for us to move away from overriding styles of public components, in favour of a keeping these components decoupled. This would reduce the complexity of our styling and make public components like `FlatTable` less prone to regressions if we change their current dependents.

File: playwright/components/flat-table/index.ts [hunk 4]
```diff
@@ -74,7 +74,9 @@ export const flatTableCurrentPageInput = (page: Page) =>
 export const flatTableRowHeader = (page: Page) =>
   page.locator(FLAT_TABLE_STICKY_ROW);
 export const flatTableHeaderCellsIcon = (page: Page) =>
-  flatTableHeader(page).locator("th > div > div").locator("span");
+  flatTableHeader(page).locator("th > div > div > span[data-component='icon']");
```
Comment (Parsium) [inline playwright/components/flat-table/index.ts]: **suggestion**: could we use a test attribute here, similar to what @nuria1110 suggested earlier? This would help make our tests more robust by being less dependent on a complex page structure.

Comment (damienrobson-sage) [reply playwright/components/flat-table/index.ts]: As discussed, I've removed this selector and accompanying test given it was only checking that a passed-in, user-specified icon rendered correctly

**Review by nuria1110 — DISMISSED** [review]
