### PR TITLE
fix(dialog, sidebar): ensure aria-modal is only added to top modal

### LINKED ISSUE #5303: Voiceover not reading elements for nested DialogFullScreen component in Safari browser
### Current behaviour

When a child `DialogFullScreen` component is nested within a parent `DialogFullScreen` component, Voiceover does not read out elements in the child `DialogFullScreen` component using Safari browser.

### Expected behaviour

When a child `DialogFullScreen` component is nested within a parent `DialogFullScreen` component, expect Voiceover to read out elements in the child `DialogFullScreen` component using Safari browser.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/voiceover-dialog-i64x57?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-31787

### Suggested Solution

_No response_

### Carbon Version

109.0.0

### Design Tokens Version

_No response_

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by robinzigmond**
Currently we add aria-modal=true to the container div of each modal component (dialog, dialog-full-screen, sidebar). This ensures screenreaders do not announce content outside the modal. However when opening one modal from another, VoiceOver on Safari refuses to read the content on the new modal while the old one still has aria-modal=true. The workaround is to ensure aria-modal=true only appears on whatever the current top modal is. This requires keeping track of the current top modal in a context which has been added to CarbonProvider, as well as keeping a global list of "top modal setters" in the window object to ensure that multiple Carbon Providers in the same application (potentially even from different versions of Carbon) still update each other's context correctly.

fix #5303

### Proposed behaviour

aria-modal=true should only be present on at most one modal (dialog/dialogfullscreen/sidebar) at a time - whichever one is currently on top of a stack of modals

VoiceOver on Safari should correctly announce a new modal when opened,  whether from another modal or not.

### Current behaviour

aria-modal=true is placed on all modals. VoiceOver on Safari will not inform the user about a modal opening when opened from another modal.

### Checklist

- [X] Commits follow our style guide
- [X] Related issues linked in commit messages if required
- [X] Screenshots are included in the PR if useful
- [X] All themes are supported if required
- [X] Unit tests added or updated if required
- [X] Cypress automation tests added or updated if required
- [X] Storybook added or updated if required
- [X] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [X] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

Test with all supported browser/screenreader combinations, as well as without a screenreader, to ensure that situations with multiple dialog/sidebar components work as expected.

If possible, test with multiple CarbonProviders wrapping different parts of an application and ensure that everything still works correctly, with aria-modal only ever applied to one modal (but is always applied to any just-opened modal).

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

File: src/components/carbon-provider/top-modal-context.tsx [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+export const TopModalContextProvider = ({
+  children,
+}: {
+  children: ReactNode;
+}) => {
+  const [topModal, setTopModal] = useState<HTMLElement | null>(null);
+
+  // can't add the setter to the global list inside useEffect because that doesn't run until
+  // after the render. Use useMemo instead so that it only runs once.
+  useMemo(() => {
```
Comment (mkrds) [inline src/components/carbon-provider/top-modal-context.tsx:26]: https://reactjs.org/docs/hooks-reference.html#usememo

`You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.`

It looks like use of `useMemo` does not guarantee that it's going to run only once.

Comment (mkrds) [reply src/components/carbon-provider/top-modal-context.tsx:26]: Also I think it would actually be better to contain that logic inside of `modal-manager` or `useModalManager` files, just pass the the `setTopModal` method through the context

Comment (robinzigmond) [reply src/components/carbon-provider/top-modal-context.tsx:26]: thanks. I'd forgotten useMemo isn't a guarantee. I guess I'll once again have to rethink how to do this.

As for your other comment - just passing setTopModal through the context doesn't work, we need to keep a global record of all such setters in order to ensure that when a modal is opened or closed in one MFE, it updates the topModal context in all others. I'm open to moving the logic to ModalManager though if it makes sense - I'll look at that.

Comment (edleeks87) [reply src/components/carbon-provider/top-modal-context.tsx:26]: You might be able to do something with `useRef` to create the equivalent of a `componentWillMount` hook.

```
useBeforeMount(setter) => {
  const mounted = useRef(false)

  if (!mounted.current) {
    if (!window.__CARBON_INTERNALS_MODAL_SETTER_LIST) {
      window.__CARBON_INTERNALS_MODAL_SETTER_LIST = [];
    }

    window.__CARBON_INTERNALS_MODAL_SETTER_LIST.push(setter);
  }
  mounted.current = true
}
```

File: src/components/carbon-provider/carbon-provider.component.tsx [hunk 2]
```diff
@@ -20,14 +22,16 @@ export const CarbonProvider = ({
...
-}: CarbonProviderProps) => (
-  <ThemeProvider theme={theme}>
-    <CarbonScopedTokensProvider>
-      <NewValidationContext.Provider value={{ validationRedesignOptIn }}>
-        {children}
-      </NewValidationContext.Provider>
-    </CarbonScopedTokensProvider>
-  </ThemeProvider>
-);
+}: CarbonProviderProps) => {
```
[the remark this answers is not in the document]
Comment (robinzigmond) [reply src/components/carbon-provider/carbon-provider.component.tsx:25]: nope, definitely not. Thanks for catching this, it's only because I initially put the TopModalContext stuff in there before pulling it out to its own component - at that point it obviously needed the longhand function body but I forgot to change this back when I refactored.

**Review by edleeks87 — DISMISSED** [review]

File: src/components/carbon-provider/top-modal-context.tsx (hunk 1 above)
Comment (mkrds) [reply src/components/carbon-provider/top-modal-context.tsx]: @robinzigmond I don't really understand what is the issue with passing down the `setTopModal` through the context to the `useModalManager` for the sake of having that logic contained in one place.

**Review by mkrds — APPROVED** [review]

**Review by ZhuoyuJin — DISMISSED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by mkrds — APPROVED** [review]

**Review by ZhuoyuJin — APPROVED** [review]
