### PR TITLE
fix(select): resolve ARIA issues (FE-4300)

### LINKED ISSUE #4339: VoiceOver for Select component reads it's textbox instead of listbox popup
### Current behaviour

When focus on Select component VoiceOver reads it's textbox component. VoiceOver also reads only name of option.

### Expected behaviour

VoiceOver should read that it's listbox popup and should add how many options in the select are e.g Option First (1 of 4).

### CodeSandbox or Storybook URL

https://codesandbox.io/s/interesting-thompson-iuhjq

### Suggested Solution

_No response_

### Carbon Version

82.0.0

### What browsers are you seeing the problem on?

Safari

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### LINKED ISSUE #4356: Select options only saying parts of an options text on Voiceover (firefox only)
### Current behaviour

Currently if we run Mac Catalina Voiceover on Firefox against a Select component that has options with multiple words only parts of the text are read. E.g; for option `Amber some` only `Amber` was read. 

### Expected behaviour

It is expected that the full option text would be read. E.g. for option `Amber some` expect `Amber some` to be read.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/cool-goodall-cv9m0

### Suggested Solution

_No response_

### Carbon Version

76.1.3

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by grabkowski**
### Proposed behaviour
Hide input field to remove caret in Select.
Add missing ARIA attributes in Select, FilterableSelect and MultiSelect.

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
~~- [ ] Screenshots are included in the PR if useful~~
~~- [ ] All themes are supported if required~~
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
~~- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required~~
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context
Fixes #4339
Fixes #4356

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

File: src/components/select/__internal__/select-text/select-text.component.js [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+      disabled={disabled}
+      hasPlaceholder={hasPlaceholder}
+      id={textId}
+      onBlur={inputContext.onBlur}
+      onClick={onClick}
+      onFocus={inputContext.onFocus}
+      onKeyDown={onKeyDown}
+      readOnly={readOnly}
+      role="button"
+      tabIndex="0"
```
Comment (edleeks87) [inline src/components/select/__internal__/select-text/select-text.component.js:39]: I think this will create two tab stops with the input and this span, so users will have to tab twice to move past the `Select` when it renders the `SelectText` element

File: src/components/select/select-textbox/select-textbox.component.js [hunk 2]
```diff
@@ -13,11 +15,15 @@ const SelectTextbox = ({
   onClick,
   onFocus,
   onBlur,
+  onChange,
   selectedValue,
   required,
+  hasTextCursor,
```
Comment (edleeks87) [inline src/components/select/select-textbox/select-textbox.component.js:21]: Would be good to have this defined in the prop table with `@ignore @private` so it documents what it does to anyone working on Select down the line

**Review by edleeks87 — COMMENTED** [review]
Can you add a `d.ts` file for the `SelectText` component please, even though it's `_internal__` it will be useful when we come to migrate to TS. I alos had a little play around with the voiceover (chrome) and notice that whilst there's a significant improvement it occasionally trims some of the text values like below:

image

File: src/components/select/__internal__/select-text/select-text.component.js (hunk 1 above)
Comment (grabkowski) [reply src/components/select/__internal__/select-text/select-text.component.js:39]: input has index of -1

**Comment by samtjo** [comment]
Can you link the Github issue to be closed by this please @grabkowski

File: cypress/features/regression/filterableSelect.feature [hunk 3]
```diff
@@ -147,8 +147,8 @@ Feature: Filterable Select component
   @positive
   Scenario: Check the onKeyDown event after clicking arrow
     Given I open "Select filterable" component page "default story"
-    When I focus default Select input
-      And I click onto default select using "downarrow" key
+    When I click on controlled Select input
+      And I click onto controlled select using "downarrow" key
```
Comment (sianford) [inline cypress/features/regression/filterableSelect.feature:151]: Can this be amended to "press downarrow onto controlled select" or something similar rather than "click onto...using downarrow" to more accurately describe the action?

File: cypress/features/regression/multiSelect.feature [hunk 4]
```diff
@@ -143,8 +143,8 @@ Feature: Multi Select component
   @positive
   Scenario: Check the onKeyDown event after clicking arrow
     Given I open "Select multiselect" component page "default story"
-    When I focus default Select input
-      And I click onto default select using "downarrow" key
+    When I click on controlled Select input
+      And I click onto controlled select using "downarrow" key
```
Comment (sianford) [inline cypress/features/regression/multiSelect.feature:147]: As above, regarding "click' with a downarrow key.

File: cypress/features/regression/filterableSelect.feature (hunk 3 above)
Comment (DlgSHi) [reply cypress/features/regression/filterableSelect.feature:151]: how would you prefer to name it ?

File: cypress/features/regression/multiSelect.feature (hunk 4 above)
Comment (DlgSHi) [reply cypress/features/regression/multiSelect.feature:147]: how would you prefer to name it ?

**Review by edleeks87 — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]

File: cypress/features/regression/multiSelect.feature (hunk 4 above)
Comment (sianford) [reply cypress/features/regression/multiSelect.feature:147]: How about `And I press "downarrow" key on controlled select` as you don't click the downarrow key, you press it.

**Review by edleeks87 — APPROVED** [review]

**Review by mkrds — APPROVED** [review]

**Review by mkrds — DISMISSED** [review]

**Review by edleeks87 — APPROVED** [review]

File: cypress/support/step-definitions/flat-table-steps.js [hunk 5]
```diff
@@ -275,11 +276,22 @@ Then("{int} row/rows is/are visible", (int) => {
...
 
 Then("Pagination input should have {int} value", (value) => {
-  pageSelectDataComponent().find("input").should("have.value", value);
+  pageSelectInput().should("have.value", value);
+});
+
+When("I press downarrow onto pagination select list", () => {
+  pageSelectInput().trigger("keydown", {
+    ...keyCode("downarrow"),
+    force: true,
```
Comment (DlgSHi) [inline cypress/support/step-definitions/flat-table-steps.js:289]: why we need to pass `force` here ?

File: cypress/support/step-definitions/select-steps.js [hunk 6]
```diff
@@ -25,48 +22,30 @@ import {
...
-Then("{string} Select list is opened", (name) => {
-  selectDataComponent(name).should("have.attr", "aria-expanded", "true");
+Then("{string} list is open", () => {
+  selectInput().should("have.attr", "aria-expanded", "true");
   selectList().should("be.visible");
 });
 
-Then("{string} Select list is closed", (name) => {
-  selectDataComponent(name).should("have.attr", "aria-expanded", "false");
+Then("{string} list is closed", () => {
```
Comment (DlgSHi) [inline cypress/support/step-definitions/select-steps.js:30]: `{string}` is useless here - because we are not providing it down to the TC

File: cypress/support/step-definitions/select-steps.js [hunk 7]
```diff
@@ -84,11 +63,11 @@ When("{string} option on the list is highlighted", (position) => {
...
 
 When("I click onto controlled select using {string} key", (key) => {
-  simpleSelectID().trigger("keydown", keyCode(key));
+  commonDataElementInputPreview().trigger("keydown", keyCode(key));
 });
 
-When("I click onto default select using {string} key", (key) => {
-  simpleSelect().trigger("keydown", keyCode(key));
+When("I press the {string} key, when focused on the input", (key) => {
+  selectInput().trigger("keydown", { ...keyCode(key), force: true });
```
Comment (DlgSHi) [inline cypress/support/step-definitions/select-steps.js:70]: the same question about `force` here :)

File: cypress/support/step-definitions/flat-table-steps.js (hunk 5 above)
Comment (grabkowski) [reply cypress/support/step-definitions/flat-table-steps.js:289]: input is covered by a span element to hide the caret when hovering over the element, yet the input is still an element that is focused and accessed when using keyboard to be ARIA compatible

File: cypress/support/step-definitions/select-steps.js (hunk 7 above)
Comment (grabkowski) [reply cypress/support/step-definitions/select-steps.js:70]: to hide the caret and still be ARIA compatible

File: cypress/support/step-definitions/select-steps.js (hunk 6 above)
Comment (grabkowski) [reply cypress/support/step-definitions/select-steps.js:30]: it's being used in three separate components, and we're providing their names here

**Review by mkrds — APPROVED** [review]

**Review by edleeks87 — DISMISSED** [review]

**Review by edleeks87 — DISMISSED** [review]

**Review by mkrds — DISMISSED** [review]

**Review by mkrds — APPROVED** [review]

**Comment by tempertemper** [comment]
Happy with the simple select behaviour and the enhancements made to the filterable select and multiselect variants. Filterable select and multiselect still need some UX attention, and this will be raised with the design team.

**Review by edleeks87 — DISMISSED** [review]

**Review by edleeks87 — DISMISSED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by sianford — APPROVED** [review]
Tested in Safari with VoiceOver and Chrome, Edge and Firefox with NVDA. All list options are read out correctly by both screen readers in all four browsers and behaving in accordance with with the ARIA guidelines and specs ✅

**Review by mkrds — APPROVED** [review]
