### PR TITLE
fix(link): refactor styles to remove focus-within due to issues with JSDOM FE-6217

### LINKED ISSUE #6320: Focus-Within usage within new Link styling
### Current behaviour

119.11.0 introduced new focus sttlying for Link:
https://github.com/Sage/carbon/commit/ae68d8debbfcfa4239096569e738de95773d3d16#diff-4bc76552ffc1900364db75add9c449feb3aedea8878cb1f0255d5816f8c5247fR169

and added focus-within.
This has known issues with jsdom and React Testing Library meaning the UI cannot query role/text of any Link component without opting out of the redesign.

### Expected behaviour

Link styling to use focus or other alternative without known issues with jsdom

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/docs/link--default-story

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

Link styling to use focus or other alternative without known issues with jsdom

### Carbon Version

119.11.0 and higher

### Design Tokens Version

_No response_

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

Chatted with @Parsium on this matter

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by edleeks87**
fix #6320

### Proposed behaviour

Refactor new focus styling for `Link` to avoid `focus-within` as it creates issues when running tests in JSDOM.
Ensures `text-decoration` is `none` when new focus styling applied
Fixes test story `icon` dropdown

image

### Current behaviour

New focus styling uses `focus-within`
`text-decoration` is `underline` when new focus styling applied
Test story `icon` dropdown is broken

image

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] Unit tests added or updated if required
- [x] Storybook added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

**Review by DipperTheDan — DISMISSED** [review]

File: src/components/link/link.component.tsx [hunk 1]
```diff
@@ -160,13 +161,16 @@ export const Link = React.forwardRef<
           ? {
               ...componentProps,
               ...buttonProps,
-              placeholderTabIndex,
+              onFocus: () => setHasFocus(true),
```
Comment (robinzigmond) [inline src/components/link/link.component.tsx:164]: **suggestion** (non-blocking): you could move these `onFocus` and `onBlur` into `componentProps` so you don't have to repeat them in both objects. This seems especially sensible to me since event handlers like `onClick` and `onKeyDown` are already there.

**Review by robinzigmond — COMMENTED** [review]
Don't know if this is an oversight or something we've got another ticket for, but just in case - I've seen we still have `focus-within` styles inside `MenuItem`. I'd rather get that fixed in the same PR, unless it's significantly more effort to do that (happy to leave it up to you, I'm mostly mentioning it in case it's something you're not aware of).

**Review by robinzigmond — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by ZhuoyuJin — APPROVED** [review]
