### PR TITLE
fix(vertical-divider): render component as li element if it is a child of Menu FE-5039

### LINKED ISSUE #4951: [Vertical Divider] axe violation found in-a-menu
### Current behaviour

List element has direct children that are not allowed inside

Screenshot 2022-03-09 at 22 49 03

### Expected behaviour

No axe violation should occur.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/verticaldivider--in-a-menu

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by edleeks87**
fix #4951

### Proposed behaviour

Wraps `VerticalDivider` in a `MenuContext.Consumer` and uses `as` prop to render wrapper as `li` element if
detected that it is a child of `Menu`
Converts `VerticalDivider` files to TypeScript

### Current behaviour

Renders as a div element
Component files ar JS

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Unit tests added or updated if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

Test that `verticaldivider--in-a-menu` story renders divider as `li` with `aria-hidden=true` and no axe warning exists
Test that other stories that don't have `Menu` render divider as `div` and `aria-hidden=false`
Test that no visual regressions in `VerticalDivider` stories following migration to TS

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

File: src/components/menu/menu.component.js [hunk 1]
```diff
@@ -55,6 +55,7 @@ const Menu = ({ menuType = "light", children, ...rest }) => {
               menuType,
               handleKeyDown: (ev) => handleKeyDown(ev, index),
               isFocused,
+              inMenu: true,
```
Comment (samtjo) [inline src/components/menu/menu.component.js:58]: You also need to set this in `MenuFullScreen` in the other Provider, otherwise any vertical dividers in a full screen menu won't pick this up

File: src/components/vertical-divider/vertical-divider.component.tsx [hunk 2]
```diff
@@ -101,13 +104,37 @@ type TintRange =
...
 
-declare function VerticalDivider(props: VerticalDividerPropTypes): JSX.Element;
+const VerticalDivider = ({
+  h,
+  height,
+  displayInline = false,
+  tint = 80,
+  ...props
+}: VerticalDividerPropTypes): JSX.Element => (
+  <MenuContext.Consumer>
```
Comment (samtjo) [inline src/components/vertical-divider/vertical-divider.component.tsx:123]: Let's consume the context in the functional component way using the `useContext` hook instead, it makes the jsx much cleaner

File: src/components/vertical-divider/vertical-divider.component.tsx [hunk 3]
```diff
@@ -101,13 +104,37 @@ type TintRange =
   | 98
   | 99
   | 100;
+
 export interface VerticalDividerPropTypes extends SpaceProps {
   h?: number | string;
+  height?: number | string;
```
Comment (samtjo) [inline src/components/vertical-divider/vertical-divider.component.tsx:110]: Good plan adding `height` in, why on earth `h` is the original prop name I have no idea 😅

File: src/components/vertical-divider/vertical-divider.style.ts [hunk 4]
```diff
@@ -1,18 +1,19 @@
...
     height &&
     css`
-      height: ${typeof height === "string" ? `${height};` : `${height}px;`};
+      height: ${typeof height === "string" ? `${height}` : `${height}px`};
     `}
   ${({ displayInline }) => (displayInline ? "display: inline;" : "")}
 `;
 
-const StyledDivider = styled.div`
+const StyledDivider = styled.div<Partial<VerticalDividerPropTypes>>`
```
Comment (samtjo) [inline src/components/vertical-divider/vertical-divider.style.ts:16]: This only needs the `tint` prop from `VerticalDividerPropTypes` - let's use `Pick` to grab only that one from `VerticalDividerPropTypes`

**Review by samtjo — CHANGES_REQUESTED** [review]

**Review by samtjo — DISMISSED** [review]

**Review by grabkowski — DISMISSED** [review]

**Review by DlgSHi — APPROVED** [review]

**Review by DlgSHi — APPROVED** [review]

**Review by grabkowski — APPROVED** [review]

**Review by samtjo — APPROVED** [review]
