### PR TITLE
fix(textarea): ensure that correct height is applied when rows and expandable prop are used together - FE-6810

### LINKED ISSUE #6961: Number of rows is not being applied to textarea
### Description

I am adding a number of `rows` to a `textarea` however this is not making the `textarea` bigger

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-7zwgav?file=src%2FApp.tsx

### Steps to reproduce

_No response_

### JIRA ticket numbers (Sage only)

_No response_

### Suggested solution

_No response_

### Carbon version

142.9.1

### Design tokens version

_No response_

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Additional context

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by DipperTheDan**
This fix ensures that when the `rows` prop and `expandable` prop are used simultaneously, the textarea component renders with the correct height.

fixes #6961

### Proposed behaviour

Screenshot 2024-09-20 at 13 57 22

### Current behaviour

Screenshot 2024-09-20 at 13 58 09

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Playwright automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

I have opted to go with a Chromatic snapshot to cover us in the event of any regression happening and reintroducing this bug. 

### Testing instructions

- Ensure that the new Chromatic snapshot for `With expandable and rows in a dialog with form` is sufficient.
- No other visual or functional regressions with Textarea.
- No other visual or functional regressions with Textarea especially when `minHeight`, `rows` or `expandable` props are used.

### CODE REVIEW

**Review by tomdavies73 — DISMISSED** [review]

File: src/components/textarea/textarea.component.tsx [hunk 1]
```diff
@@ -264,7 +264,7 @@ export const Textarea = React.forwardRef(
 
         const scrollPosition = scrollElement?.scrollTop;
 
-        textarea.style.height = "0px";
+        if (!rows && expandable) textarea.style.height = "0px";
```
Comment (Parsium) [inline src/components/textarea/textarea.component.tsx:267]: **suggestion(non-blocking)**: it appears this line was added a while ago to get round some default behaviour in IE. Given we don't support IE anymore, what do you think about removing this?


```suggestion
```

Comment (DipperTheDan) [reply src/components/textarea/textarea.component.tsx:267]: Yeah, I saw it was a legacy thing when I investigated why it was in the code in the first place. I can delete it and see if anything breaks. If nothing breaks, I'll happily remove it 😄

**Review by Parsium — APPROVED** [review]

**Review by tomdavies73 — DISMISSED** [review]

**Review by paulrobinson88 — APPROVED** [review]

**Review by Parsium — APPROVED** [review]

**Review by tomdavies73 — APPROVED** [review]
