### PR TITLE
fix(menu-item): address aria role accessibility error with icon only menu items - FE-6055

### LINKED ISSUE #4986: Menu with icon - Accessibility violations "Elements must only use allowed ARIA attributes"
### Current behaviour

One accessibility violation in "with icon" story for Menu componen
Image 22-03-2022 at 12 37
t

### Expected behaviour

No Accessibility violations

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/menu--with-icon

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### LINKED ISSUE #6175: Menu - Accessibility violation in the 'with icon' story
### Current behaviour

There is an accessibility violation for reason "Elements must only use allowed ARIA attributes" in the 'with icon' story.

Screenshot 2023-07-05 at 16 44 45

### Expected behaviour

There are no accessibility violations in the Menu component.

### CodeSandbox or Storybook URL

https://carbon.sage.com/?path=/story/menu--with-icon-story

### JIRA Ticket (Sage Only)

FE-6048

### Suggested Solution

Resolve violation.

### Carbon Version

119.5.0

### Design Tokens Version

_No response_

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by DipperTheDan**
`Elements must only use allowed ARIA attributes` error was occurring in an example of Menu with icon only menu items. This was due to the aria-label being specified on the anchor element and also the underlying span element of the icon itself.

fixes #6175
fixes #4986

### Proposed behaviour

Address "Elements must only use allowed ARIA attributes" warning on `with icon` Menu story.

### Current behaviour

`with icon` Menu story has an accessibility error of "Elements must only use allowed ARIA attributes".

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Playwright automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

N/A

### Testing instructions

- `with icon` Story should have no accessibility errors. 
- Should be no regression of features or screenreader behaviour in `menu-item`, `link` and `icon`.

### CODE REVIEW

File: src/components/icon/icon.component.tsx [hunk 1]
```diff
@@ -156,6 +159,7 @@ const Icon = React.forwardRef<HTMLSpanElement, IconProps>(
       disabled: disabledFromContext || disabled,
       fontSize,
       hasTooltip,
+      hideAriaLabel,
```
Comment (robinzigmond) [inline src/components/icon/icon.component.tsx:162]: **question**: I'm probably being stupid again here - but why does `hideAriaLabel` need to go down to the underlying styled component (a `span` in this case)? It doesn't appear to use it, and no styles will depend on it as far as I can see - nor is it a valid HTML attribute.

File: src/components/link/link.component.tsx [hunk 2]
```diff
@@ -109,6 +112,7 @@ export const Link = React.forwardRef<
           type={icon}
           bgSize="extra-small"
           disabled={disabled}
+          hideAriaLabel={hideAriaLabel}
```
Comment (robinzigmond) [inline src/components/link/link.component.tsx:115]: **question**: I could well be missing something, but can't we just change the `ariaLabel={ariaLabel}` to `ariaLabel={hideAriaLabel ? undefined : ariaLabel}`, to avoid needing a `hideAriaLabel` prop at all on `Icon`? (You'd still need it on Link though, assuming you ever wanted a <span> with an incorrect aria-label for an icon inside a Link.)

File: src/components/menu/menu-item/menu-item.component.tsx [hunk 3]
```diff
@@ -242,6 +242,7 @@ export const MenuItem = ({
     rel,
     onClick,
     icon,
+    hideAriaLabel: true,
```
Comment (robinzigmond) [inline src/components/menu/menu-item/menu-item.component.tsx:245]: **suggestion**: (this isn't about this line of code in particular but seems the best place I can find to put it)

I think it's worth adding a test for MenuItem specifically, that we don't end up with an aria-label on the StyledIcon when rendering an icon. I know you have the test for the new prop on Icon itself, and that will satisfy coverage, but you're nowhere testing that we're actually applying this in MenuItem, and that was after all what the ticket is really about.

File: src/components/icon/icon.component.tsx [hunk 4]
```diff
@@ -55,6 +55,8 @@ export interface IconProps extends Omit<StyledIconProps, "type">, MarginProps {
   inputSize?: "small" | "medium" | "large";
   /** @ignore @private */
   tabIndex?: number;
+  /** @ignore @private internal prop to be used in the event no aria-label should be specified */
+  hideAriaLabel?: boolean;
```
[the remark this answers is not in the document]
Comment (DipperTheDan) [reply src/components/icon/icon.component.tsx:59]: Yeah I had considered tearing out the aria-label out of `Icon` all together but this would be a breaking change as aria-label is advertised as a prop. I figured for now being able to hide the aria-label where we needed to would suffice. I had checked that if I removed the aria-label from `Icon` would it also address the `Pod` issue too but it didn't. Hence I went for this approach instead.

File: src/components/link/link.component.tsx [hunk 5]
```diff
@@ -49,6 +49,8 @@ export interface LinkProps extends StyledLinkProps, React.AriaAttributes {
   rel?: string;
   /** @ignore @private internal prop to be set when no href or onClick passed */
   placeholderTabIndex?: boolean;
+  /** @ignore @private internal prop to be set when no aria-label should be specified */
+  hideAriaLabel?: boolean;
```
[the remark this answers is not in the document]
Comment (DipperTheDan) [reply src/components/link/link.component.tsx:53]: I'll go with `removeAriaLabelFromIcon` 👍🏻

File: src/components/icon/icon.spec.tsx [hunk 6]
```diff
@@ -470,6 +470,18 @@ describe("Icon component", () => {
       );
     });
 
+    it("does not set an aria label if hideAriaLabel is true", () => {
+      const wrapper = mount(
+        <Icon type="home" hideAriaLabel ariaLabel="home" />
+      );
+
+      expect(wrapper.find(StyledIcon).props()).toEqual(
```
[the remark this answers is not in the document]
Comment (DipperTheDan) [reply src/components/icon/icon.spec.tsx:478]: I went for this because it's the same format that is used to test the `aria-label` further up in the tests so I wanted to keep things congruent. I am happy to change it your way though.

File: src/components/link/link.component.tsx (hunk 2 above)
Comment (DipperTheDan) [reply src/components/link/link.component.tsx:115]: I'll message you privately about this as It'll need some further explaining.

File: src/components/menu/menu-item/menu-item.component.tsx (hunk 3 above)
Comment (DipperTheDan) [reply src/components/menu/menu-item/menu-item.component.tsx:245]: The reason I tested it on `Icon` was that it wasn't technically `MenuItem` that had the bug. The bug came from `Link` which in turn came from `Icon` getting a aria-label set. I'll get a test added to `MenuItem` though as it's not that big of a job to do for the extra piece of mind it can give us 👍🏻

File: src/components/icon/icon.spec.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (robinzigmond) [reply src/components/icon/icon.spec.tsx:478]: fair enough, I'd missed that. Personally I'd still write this test what I think is the better way, and maybe even change the other one - but it doesn't really matter. (The one scenario that does matter is if somehow the icon ended up with an aria-label taht was different from the one passed in the prop - then your test would pass while my suggestion would fail. But that's such an out-there situation I'm not going to try to use this as a serious argument in favour of mine 😂 )

File: src/components/menu/menu-item/menu-item.component.tsx (hunk 3 above)
Comment (robinzigmond) [reply src/components/menu/menu-item/menu-item.component.tsx:245]: Actually you're right that it's Link where the bug actually was, so a test on that is not a bad idea. I'd definitely prefer to have one on either that or Menuitem (or even both, but probably no need), than neither, though 👍

Comment (DipperTheDan) [reply src/components/menu/menu-item/menu-item.component.tsx]: I've amended one on `MenuItem` and added one to `Link` based on the changes made in the last commit. So we're covered for both now.

`MenuItem` checks `Link` and `Icon`.
`Link` checks `Link` and `Icon`.

So if a regression happens in `Link` or `MenuItem`, we'll know about it 👍🏻

File: src/components/icon/icon.spec.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (DipperTheDan) [reply src/components/icon/icon.spec.tsx]: Changed the unit tests as per the other suggested changes so this was kind of redundant now.

File: src/components/icon/icon.component.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (DipperTheDan) [reply src/components/icon/icon.component.tsx]: Changed this approach to having `aria-label={undefined}` now passed from `Link`. I've removed this prop from `Icon` now based on the other suggested changes.

File: src/components/link/link.spec.tsx [hunk 7]
```diff
@@ -293,6 +293,18 @@ describe("Link", () => {
         expect(anchor.getAttribute("aria-label")).toEqual("test");
       });
     });
+
+    describe("when removeAriaLabelOnIcon is true", () => {
+      it("should set aria-label as undefined on icon", () => {
+        wrapper = renderLink({
```
Comment (robinzigmond) [inline src/components/link/link.spec.tsx:299]: **suggestion** (non-blocking): I would feel this test was much more robust if we also passed an `ariaLabel` prop to the Link, to ensure that the `removeAriaLabelOnIcon` is really doing its job

Comment (DipperTheDan) [reply src/components/link/link.spec.tsx:299]: Not an unreasonable suggestion and makes sense from a robustness perspective. I'll get it done now and pushed back up 👍🏻

**Review by robinzigmond — APPROVED** [review]

**Review by Parsium — APPROVED** [review]
Looks good to me 👍🏼 

As it seems `MenuItem` is coupled to the internal styled components of `Link` and `Icon`, which appears to be partly responsible for the bug, it might be worth us doing some refactoring in the future to decouple `MenuItem` from these internals.

**Review by divyajindel — APPROVED** [review]
Looks good to me!
