### PR TITLE
fix(tile-select): ensure title, subtitle and adornment wrap at smaller screen resolution FE-4275

### LINKED ISSUE #4219: TileSelect component pill overlapping custom button
### Current behaviour

When a Tile Select component is used with long header contents (title, subtitle and pill) the pill will overlap a custom action button as shown below in screenshot:
Screenshot 2021-07-06 at 14 02 17

### Expected behaviour

TileSelect components to render correctly without overlap

### Reproducible example
https://codesandbox.io/s/snowy-star-9529v?file=/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | v77.2.2
| carbon-factory   |
| react-scripts    | 
| React            |
| Browser          | OSX Chrome
| npm              |
| Operating System |

### PR DESCRIPTION
**Pull request by edleeks87**
fix #4219

### Proposed behaviour

Adds `flow-wrap` style property to container for `title`, `subtitle` and `adornment` to ensure they
wrap at smaller resolution or if any text is too long. Adds flex `Box` to wrap the the above content
and the action button so they render in correct layout.

Adds `prefixAdornment` prop to allow implementation teams to render a node in the top left corner of
`TileSelect` before other content.

### Current behaviour

Content does not wrap (see linked issue)
No support for prefix adornment

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Additional context

image

image

### Testing instructions

`design-system-tile-select--with-a-prefix-adornment` added.

Demo of wrapping:
https://codesandbox.io/s/eloquent-snyder-6d2gt?file=/src/index.js

### CODE REVIEW

File: src/components/tile-select/tile-select.component.js [hunk 1]
```diff
@@ -111,37 +113,41 @@ const TileSelect = ({
...
-                {title}
-              </StyledTitle>
-            )}
+          <Box display="flex" justifyContent="space-between">
+            {prefixAdornment && <Box mr={3}>{prefixAdornment}</Box>}
+            <Box flexGrow="1">
+              <StyledTitleContainer>
+                {title && (
+                  <StyledTitle
+                    {...(typeof title !== "string" && { as: "div" })}
```
Comment (mmaciorowski-sage) [inline src/components/tile-select/tile-select.component.js:122]: it would be nice to have a function like
```
(element) => typeof element !== "string" && { as: "div" }
```

Comment (edleeks87) [reply src/components/tile-select/tile-select.component.js:122]: Yeah that's a good idea I'll update it after another reviewer has looked at the PR

**Review by mmaciorowski-sage — DISMISSED** [review]

**Review by dawidzarzycki — DISMISSED** [review]

**Review by dawidzarzycki — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by divyajindel — APPROVED** [review]
