### PR TITLE
fix(split-button, multi-action-button): ensure autoUpdate does not run when popover is closed

### LINKED ISSUE #7802: MultiActionButton/SplitButton - conditional rendering for additional buttons
### Description

Carbon v158.27.1 via PR [#7733](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) changed MultiActionButton and SplitButton from conditional rendering to always-rendered (hidden via hidden attribute).
```
- {showAdditionalButtons && renderAdditionalButtons()}
+ {renderAdditionalButtons()}
```

But the Popover wrapping the additional buttons never receives isOpen={showAdditionalButtons} — it defaults to isOpen={true}.

Impact

- useFloating runs its useLayoutEffect on every render even when the popup is closed
- autoUpdate from @floating-ui/dom sets up ResizeObserver + scroll/resize listeners permanently
- The middleware array is recreated inline each render (new reference), retriggering the effect cleanup + setup cycle
- Combined with the mock ResizeObserver (which fires synchronously on observe()), this creates significant event loop overhead in tests

This causes time-sensitive tests to flake or timeout on CI (or by running all tests on multiple terminals at the same time in local), even in consumers that don't interact with the MultiActionButton/SplitButton directly — just having one rendered on the page is enough.

Suggested fix
Pass isOpen to Popover in both components:
// multi-action-button.component.tsx & split-button.component.tsx
```
<Popover
  isOpen={showAdditionalButtons}  // ← add this
  disableBackgroundUI={isInFlatTable}
  disablePortal
  ...
>
```

### Reproduction

https://sageone.slack.com/archives/C0D6DD3N2/p1772120659795039

### Steps to reproduce

_No response_

### JIRA ticket numbers (Sage only)

_No response_

### Suggested solution

_No response_

### Carbon version

158.27.1

### React version

v18

### Design tokens version

_No response_

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Assistive technologies

_No response_

### Additional context

_No response_

### Confidentiality

- [x] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by nuria1110**
fix: #7802

### Proposed behaviour

In SplitButton and MultiActionButton:
- `autoUpdate` only runs if the popover is open
- memoize middleware array
- ensure resize and scroll event listeners are only set up when popover is open

### Current behaviour

In SplitButton and MultiActionButton:
- `autoUpdate` is called even if popover is closed
- middleware array is recreated on every re-render
- resize observers are permanently set up

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

- `SelectList` has been impacted by some of the changes but there should be no visual or functional changes. 
- All components using `Popover` internally should have no detectable changes to consumers. 
-`SplitButton` and `MultiActionButton` to be tested with VO - should have no changes to behaviour.

### CODE REVIEW

**Review by DipperTheDan — APPROVED** [review]

File: src/components/split-button/split-button.component.tsx [hunk 1]
```diff
@@ -217,8 +218,19 @@ export const SplitButton = forwardRef<SplitButtonHandle, SplitButtonProps>(
       </>
     );
 
+    const floatingMiddleware = useMemo(
```
Comment (tomdavies73) [inline src/components/split-button/split-button.component.tsx:221]: **praise**: good shout memoising this

**Review by tomdavies73 — APPROVED** [review]

**Review by dariusbercea-sage — APPROVED** [review]
