### PR TITLE
fix(popover-container): remove incorrect role attribute - FE-5249

### LINKED ISSUE #5286: FlatTable / PopoverContainer - Axe Violation - Ensures landmarks are unique
### Current behaviour

FlatTable with PopoverContainer has an axe violation, landmarks should have a unique role or role/label/title (i.e. accessible name) combination.

image
https://dequeuniversity.com/rules/axe/4.4/landmark-unique?application=AxeChrome

### Expected behaviour

No accessibility violations should occur.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/quizzical-fire-j3m2y0?file=/src/index.js:7745-7761

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

109.0.0

### Design Tokens Version

2.25.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by mkrds**
### Proposed behaviour

Fixes #5286 

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

https://codesandbox.io/s/runtime-fire-8s58vh

### CODE REVIEW

File: src/components/popover-container/popover-container.component.tsx [hunk 1]
```diff
@@ -25,6 +25,8 @@ export interface RenderOpenProps {
   ref: React.RefObject<HTMLButtonElement>;
   "aria-label"?: string;
   id?: string;
+  "aria-expanded": boolean;
+  "aria-haspopup": boolean;
```
Comment (DipperTheDan) [inline src/components/popover-container/popover-container.component.tsx:29]: Do we want to restrict this to just boolean when the value could also be a string like `menu`, `dialog` or `listbox`? 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup#values

**Review by robinzigmond — DISMISSED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by DipperTheDan — DISMISSED** [review]

**Review by Parsium — APPROVED** [review]

**Comment by harpalsingh** [comment]
Using provided codesandbox - https://codesandbox.io/s/runtime-fire-8s58vh - testing using Axe and landmark violation is now not presented therefore passing a11y review which this was fixing.

**Review by DlgSHi — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]
