### PR TITLE
fix(textarea, textbox): accessibility enhancements on character counter

### LINKED ISSUE #5717: Textbox characters count - Accessibility
### Desired behaviour

In Textbox or Textarea with the characterLimit functionality
Screenshot 2023-01-03 at 12 18 58
the VoiceOver reads 7/10, it would be desirable to read 3 remaining characters

### Current behaviour

the VoiceOver reads 7/10

### Suggested Solution

_No response_

### CodeSandbox or Storybook URL

_No response_

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by tomdavies73**
fix #5717

### Proposed behaviour

Screenshot 2023-02-21 at 10 36 42

Screenshot 2023-02-21 at 10 36 29

This PR will introduce a mandatory hint string before the input, which explicitly states that the input contains a character counter/limit. Also, this hint has been given a unique Id and is referenced within the Input with an `aria-describedby` attribute. This ensures users using AT will also be able to benefit from the additional information the hint provides.

Also, the wording of the actual counter below the input has now been changed from numerical to a sentence, mirroring the [GOV.UK character count component](https://design-system.service.gov.uk/components/character-count/), this sentence description will be more descriptive for users reading the string visually, but also sounds much clearer on the `aria-live` region which reads this count on change.

### Current behaviour

Screenshot 2023-02-17 at 16 23 51

Screenshot 2023-02-17 at 16 23 39

Currently there is no hint text to inform all users that the input contains a character counter/limit, and the count itself is numerical, which can may be unclear for all users, especially those using AT.

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

### CODE REVIEW

File: src/__internal__/character-count/character-count.component.tsx [hunk 1]
```diff
@@ -14,14 +15,25 @@ const CharacterCount = ({
...
-    data-element={dataElement}
-  >
-    {`${value}/${limit}`}
-  </StyledCharacterCount>
-);
+}: CharacterCountProps) => {
+  const remainingCharacters: number = +limit - +value;
+  const charactersOverLimit: number = +value - +limit;
+  const l = useLocale();
+  const remainingCharactersString = l.characterCount.remainingCharactersString();
```
Comment (DlgSHi) [inline src/__internal__/character-count/character-count.component.tsx:22]: why this is only in plural?

File: src/__internal__/character-count/character-count.spec.tsx [hunk 2]
```diff
@@ -39,4 +40,22 @@ describe("CharacterCount", () => {
       );
     });
   });
+
+  it("character count string should be correct", () => {
+    wrapper = mount(<CharacterCount value="4" limit="3" isOverLimit />);
+    expect(wrapper.find(StyledCharacterCount).text()).toBe(
+      "You have 1 characters too many"
```
Comment (DlgSHi) [inline src/__internal__/character-count/character-count.spec.tsx:47]:
```suggestion
      "You have 1 character too many"
```

File: src/__internal__/character-count/character-count.spec.tsx [hunk 3]
```diff
@@ -39,4 +40,22 @@ describe("CharacterCount", () => {
...
+    );
+  });
+
+  describe("when isOverLimit prop is false", () => {
+    it("character count string should be correct", () => {
+      wrapper = mount(
+        <CharacterCount value="2" limit="3" isOverLimit={false} />
+      );
+      expect(wrapper.find(StyledCharacterCount).text()).toBe(
+        "1 characters remaining"
```
Comment (DlgSHi) [inline src/__internal__/character-count/character-count.spec.tsx:57]:
```suggestion
        "1 character remaining"
```

File: src/locales/pl-pl.ts [hunk 4]
```diff
@@ -20,6 +20,11 @@ const plPL: Locale = {
     no: () => "Nie",
     yes: () => "Tak",
   },
+  characterCount: {
+    remainingCharactersString: () => "pozostałe znaki",
```
Comment (DlgSHi) [inline src/locales/pl-pl.ts:24]:
```suggestion
    remainingCharactersString: () => "pozostało znaków",
```

File: src/locales/pl-pl.ts [hunk 5]
```diff
@@ -20,6 +20,11 @@ const plPL: Locale = {
...
+    firstOverCharactersString: () => "Masz",
+    secondOverCharactersString: () => "zbyt wiele znaków",
```
Comment (DlgSHi) [inline src/locales/pl-pl.ts:26]:
```suggestion
    secondOverCharactersString: () => "znaków za dużo",
```

File: src/locales/pl-pl.ts [hunk 6]
```diff
@@ -59,6 +64,9 @@ const plPL: Locale = {
   heading: {
     backLinkAriaLabel: () => "Wstecz",
   },
+  hintString: {
+    primaryHintString: () => "Wejście zawiera licznik znaków",
```
Comment (DlgSHi) [inline src/locales/pl-pl.ts:68]:
```suggestion
    primaryHintString: () => "Pole zawiera licznik znaków",
```

**Review by DlgSHi — CHANGES_REQUESTED** [review]

File: src/__internal__/character-count/character-count.component.tsx (hunk 1 above)
Comment (tomdavies73) [reply src/__internal__/character-count/character-count.component.tsx:22]: Great point, I've spent most of today finding a better way to achieve this automatically, and with the use of translations

File: src/locales/pl-pl.ts [hunk 7]
```diff
@@ -20,6 +20,13 @@ const plPL: Locale = {
     no: () => "Nie",
     yes: () => "Tak",
   },
+  characterCount: {
+    youHave: () => "Masz",
+    tooMany: () => "zbyt wiele",
+    character: () => "znak",
+    characters: () => "znaki",
+    remaining: () => "pozostałe",
+  },
```
Comment (mkrds) [inline src/locales/pl-pl.ts:29]: I'm afraid that won't work for polish language (and might not work for others as well).

I think it might be better to create a template which will give users more flexibilty:


```suggestion
tooManyCharacters: (count) => count === 1 ? `Masz o ${count} znak za dużo` : `Masz o ${count} znaków za dużo`;
charactersLeft: (count) => count === 1 ? `Masz ${count} pozostały znak` : `Masz ${count} pozostałych znaków`;
```

That will also reduce the logic for gluing those words inside of the CharacterCount component

File: src/locales/pl-pl.ts (hunk 6 above)
Comment (mkrds) [reply src/locales/pl-pl.ts:70]: I think the `hintString` should be contained inside the `characterCount` field.

File: src/components/textarea/textarea.component.tsx [hunk 8]
```diff
@@ -284,9 +294,9 @@ export const Textarea = React.forwardRef(
         <Input
           aria-invalid={!!error}
           aria-labelledby={ariaLabelledBy}
-          aria-describedby={
+          aria-describedby={`${
             validationRedesignOptIn ? undefined : ariaDescribedBy
-          }
+          }${hintDescribedBy}`}
```
Comment (mkrds) [inline src/components/textarea/textarea.component.tsx:299]:
```suggestion
          } ${hintDescribedBy}`}
```
Besides I think it would be more readable you'd move the ternary conditional to a separate const like `hintDescribedBy`

File: src/components/textbox/textbox.component.tsx [hunk 9]
```diff
@@ -255,9 +265,9 @@ export const Textbox = React.forwardRef(
           align={align}
           aria-invalid={!!error}
           aria-labelledby={labelId}
-          aria-describedby={
+          aria-describedby={`${
             validationRedesignOptIn ? undefined : ariaDescribedBy
-          }
+          }${hintDescribedBy}`}
```
Comment (mkrds) [inline src/components/textbox/textbox.component.tsx:270]:
```suggestion
          } ${hintDescribedBy}`}
```

File: src/components/textarea/textarea.component.tsx [hunk 10]
```diff
@@ -354,6 +364,14 @@ export const Textarea = React.forwardRef(
               adaptiveLabelBreakpoint={adaptiveLabelBreakpoint}
               validationRedesignOptIn={validationRedesignOptIn}
             >
+              {characterLimit ? (
+                <StyledCharacterCountHint
+                  id={hintId.current}
+                  data-element="styled-character-count-hint"
```
Comment (mkrds) [inline src/components/textarea/textarea.component.tsx:370]:
```suggestion
                  data-element="character-count-hint"
```

File: src/components/textarea/textarea.component.tsx [hunk 11]
```diff
@@ -268,6 +273,11 @@ export const Textarea = React.forwardRef(
       (validationIconId && !validationOnLabel)
     );
 
+    const l = useLocale();
+    const hintString = l.hintString.primaryHintString();
+    const hintId = useRef(guid());
+    const hintDescribedBy = `${characterLimit ? hintId.current : ""}`;
```
Comment (mkrds) [inline src/components/textarea/textarea.component.tsx:279]: I've noticed that lines 276-279 are exactly the same in `textbox.component.tsx`, maybe you could move it to the `useCharacterCount` hook, and then return the `StyledCharacterCountHint` as `characterCountHint` in the same manner as `CharacterCount` is returned as `characterCount` from that hook?

File: src/components/textbox/textbox.spec.tsx [hunk 12]
```diff
@@ -38,10 +41,39 @@ describe("Textbox", () => {
     { modifier: "&&&" }
   );
 
-  it("renders a counter", () => {
-    const wrapper = mount(<Textbox value="test string" characterLimit={100} />);
+  describe(`when the characterLimit prop is passed`, () => {
+    it.each([2, 3, 4])("renders a chracter counter", (characterLimit) => {
```
Comment (DipperTheDan) [inline src/components/textbox/textbox.spec.tsx:45]:
```suggestion
    it.each([2, 3, 4])("renders a character counter", (characterLimit) => {
```

File: src/locales/pl-pl.ts (hunk 7 above)
Comment (mkrds) [reply src/locales/pl-pl.ts:33]: I forgot that polish is one of the hardest languages in the world and it won't be that simple, sorry for that :). The template idea I proposed is still valid but for the polish translation it will slightly more complex because we need to use 3 words, not just 2, `znak`, `znaki`, `znaków`.

Here's a method for that:

```
function polishPlural(singularNominativ, pluralNominativ, pluralGenitive, value) {
    if (value === 1) {
        return singularNominativ;
    } else if (value % 10 >= 2 && value % 10 <= 4 && (value % 100 < 10 || value % 100 >= 20)) {
        return pluralNominativ;
    } else {
        return pluralGenitive;
    }
}
```

And then use this method like this:

```
tooManyCharacters: (count) => `Masz o ${count} ${polishPlurals("znak", "znaki", "znaków", count) za dużo`;


charactersLeft: (count) => `Masz ${count} ${polishPlurals("pozostały", "pozostałe", "pozostałych", count) ${polishPlurals("znak", "znaki", "znaków", count)`;

```

File: src/hooks/__internal__/useCharacterCount/useCharacterCount.tsx [hunk 13]
```diff
@@ -10,10 +12,18 @@ const useCharacterCount = (
...
+  number | undefined,
+  JSX.Element | null,
+  string | undefined,
+  JSX.Element | null
+] => {
   const isCharacterLimitValid =
     typeof characterLimit === "number" && !Number.isNaN(characterLimit);
   const l = useLocale();
+  const hintString = l.characterCount.hintString();
+  const mandatoryWarn = warnOverLimit || !warnOverLimit;
```
[the remark this answers is not in the document]
Comment (tomdavies73) [reply src/hooks/__internal__/useCharacterCount/useCharacterCount.tsx:25]: Hi, I've purposely done this so the styling of the character counter is always red and bold when it is over the limit, which matches the GOV.UK component recommended by Martin. This way, whether the user passes `warnOverLimit` as true or false, the behaviour will always be the same. Be interesting to see what you think on this, and if there's any other approaches we could take. I just felt initially this was the best without leaving the prop out of the hook completely..

[the remark this answers is not in the document]
Comment (mkrds) [reply src/hooks/__internal__/useCharacterCount/useCharacterCount.tsx:25]: Hmm, ok so that looks like the `warnOverLimit` prop is not really used for anything anymore. Maybe it would be best to simply remove it?

[the remark this answers is not in the document]
Comment (mkrds) [reply src/hooks/__internal__/useCharacterCount/useCharacterCount.tsx:25]: It won't be a breaking change, you'd just have to add an info the the commit message body that `warnOverLimit` prop is no longer consumed by the component

File: src/__internal__/character-count/character-count.component.tsx [hunk 14]
```diff
@@ -9,19 +10,47 @@ interface CharacterCountProps {
   "data-element"?: string;
 }
 
+export const PolishPlural = (
```
Comment (DipperTheDan) [inline src/__internal__/character-count/character-count.component.tsx:13]: I feel this should be in it's own file separate from the component. I'm kind of worried that if we've done this for Polish, what other languages would we be expected to have a need to write a function for also?

File: src/components/textarea/textarea.stories.tsx [hunk 15]
```diff
@@ -80,12 +81,71 @@ export const UnenforcedCharacterLimitStory: ComponentStory<
...
 };
 UnenforcedCharacterLimitStory.parameters = { chromatic: { disable: true } };
 
+export const TranslationsCharacterLimitStory: ComponentStory<
+  typeof Textarea
+> = () => {
+  const [value, setValue] = useState("");
+  return (
+    <>
+      <I18nProvider
```
Comment (mkrds) [inline src/components/textarea/textarea.stories.tsx:95]: I think that example with english translations is kinda redundant considering the fact that they're exactly the same as the ones provided by us by default

File: src/components/textbox/textbox.stories.tsx [hunk 16]
```diff
@@ -28,11 +29,71 @@ export const CharacterCounter: ComponentStory<typeof Textbox> = () => {
...
+export const CharacterCounterTranslations: ComponentStory<
+  typeof Textbox
+> = () => {
+  const [state, setState] = useState("Textbox");
+  const setValue = ({ target }: React.ChangeEvent<HTMLInputElement>) => {
+    setState(target.value);
+  };
+  return (
+    <>
+      <I18nProvider
```
Comment (mkrds) [inline src/components/textbox/textbox.stories.tsx:45]: Same as in Textarea stories, the english translations override example is kinda redundant.

File: src/components/textbox/textbox.component.tsx [hunk 17]
```diff
@@ -223,6 +227,14 @@ export const Textbox = React.forwardRef(
       fieldHelp,
     });
 
+    let hintDescribedBy = `${
```
Comment (mkrds) [inline src/components/textbox/textbox.component.tsx:230]: Same as in `Textarea`, I think the readability here is low

File: src/__internal__/character-count/character-count.spec.tsx [hunk 18]
```diff
@@ -38,5 +40,47 @@ describe("CharacterCount", () => {
...
+      wrapper = mount(
+        <CharacterCount value="2" limit="3" isOverLimit={false} />
+      );
+      expect(wrapper.find(StyledCharacterCount).text()).toBe(
+        "You have 1 character remaining"
+      );
+    });
+  });
+
+  describe("PolishPlural function checks", () => {
```
[the remark this answers is not in the document]
Comment (tomdavies73) [reply src/__internal__/character-count/character-count.spec.tsx:63]: I've went for pl-pl.spec in the locales folder, but can relocate/rename if needed 👍

File: src/components/textarea/textarea.component.tsx [hunk 19]
```diff
@@ -129,7 +129,7 @@ export const Textarea = React.forwardRef(
       children,
       characterLimit,
       enforceCharacterLimit = true,
-      warnOverLimit = false,
+      warnOverLimit = true,
```
[the remark this answers is not in the document]
Comment (tomdavies73) [reply src/components/textarea/textarea.component.tsx:132]: Removed prop from all components, but still in TextareaProps/TextboxProps

**Review by mkrds — DISMISSED** [review]

**Review by DipperTheDan — DISMISSED** [review]

**Review by mkrds — APPROVED** [review]

**Review by DipperTheDan — COMMENTED** [review]
Happy to approve once the commit message has been amended to include the usual `BREAKING CHANGE: ...` message.

**Comment by DipperTheDan** [comment]
> Happy to approve once the commit message has been amended to include the usual `BREAKING CHANGE: ...` message.

Ignore this. Just noticed you already have that in your commit message 😆

**Review by DipperTheDan — DISMISSED** [review]

**Comment by harpalsingh** [comment]
Tested voiceover on Mac os

**Review by DlgSHi — DISMISSED** [review]

**Review by DlgSHi — APPROVED** [review]

**Review by mkrds — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]
