### PR TITLE
fix(pager): use activation trigger for onkeydown and onclick

### LINKED ISSUE #6289: Tab-navigation to Next button of `Pager` component triggers `onClick`
### Current behaviour

**Given** `Pager` is rendered
**When** I tab-navigate to `Next` button
**Then** I see the highlight (and I think It triggers pagination `onFocus`)
**When** I press `Enter`
**Then** I see pagination jumps from Page 1 to Page 3

### Expected behaviour

**Given** `Pager` is rendered
**When** I tab-navigate to `Next` button
**Then** I see the highlight without any event being triggered 
**When** I press `Enter`
**Then** I see pagination jumps from Page 1 to Page 2

### CodeSandbox or Storybook URL

https://jdc2vt.csb.app/

### JIRA Ticket (Sage Only)

SBS-66661

### Suggested Solution

Please could you ensure that First, Previous, Next, Last, PageSize dropdown and interactive number input don't trigger pagination `onFocus` without `onClick` or `onChange`.

### Carbon Version

120.1.0

### Design Tokens Version

4.17.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

MacOS

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by MarcServat**
fix #6289

### Proposed behaviour

Given a Pager component, and focusing on the next or previous button, when pressing Enter or Space key, then updates the page number by 1 unit. Like n = n ± 1

### Current behaviour

Given a Pager component, and focusing on the next or previous button, when pressing Enter or Space key, then onNext and onPrevious callbacks updates the page number by 2 units. Like n = n ± 2

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Playwright automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

https://stackblitz.com/edit/parsium-carbon-starter-e8jtlq?file=src%2FApp.tsx

### CODE REVIEW

File: src/components/pager/__internal__/pager-navigation.component.tsx [hunk 1]
```diff
@@ -46,7 +46,7 @@ export interface PagerNavigationProps {
       | React.KeyboardEvent<HTMLButtonElement>
   ) => void;
   /** onPagination Callback triggered when a change is triggered */
-  onPagination: (pageSize: number, currentPage: number, origin: string) => void;
+  onPagination: (currentPage: number, pageSize: number, origin: string) => void;
```
Comment (tomdavies73) [inline src/components/pager/__internal__/pager-navigation.component.tsx:49]: **issue**: I can understand that having these args ordered alphabetically is desirable, but unfortunately as this callback is already public facing by being documented and potentially already used in products this may cause some issues. If users have already passed args to the `onPagination` callback the number they have passed as the `pageSize` will now be the `currentPage` and vice versa - potentially causing unintentional behaviour.

File: src/components/link/link.component.tsx [hunk 2]
```diff
@@ -85,25 +84,6 @@ export const Link = React.forwardRef<
     const [hasFocus, setHasFocus] = useState(false);
     const l = useLocale();
     const { inMenu } = useContext(MenuContext);
-    const handleOnKeyDown = (
```
Comment (tomdavies73) [inline src/components/link/link.component.tsx:88]: **praise**: Good work Marc, this function does appear to be the culprit of the unintended behaviour, as we're calling both `onClick` and `onKeyDown` resulting in the unintended "double click" behaviour

File: cypress/components/flat-table/flat-table.cy.tsx [hunk 3]
```diff
@@ -2540,10 +2540,7 @@ context("Tests for Flat Table component", () => {
         }
       }
 
-      flatTablePageSelectNext()
-        .find("button")
-        .focus()
-        .trigger("keydown", keyCode("Space"));
+      flatTablePageSelectNext().find("button").focus().realPress("Space");
```
Comment (tomdavies73) [inline cypress/components/flat-table/flat-table.cy.tsx:2543]: **comment** (non-blocking): Just letting you know this file is currently being refactored Playwright, so there is a chance these changes may have to be re-made, however hopefully during said refactor we will use the proper and preferred keydown triggers/tests

File: src/components/pager/__internal__/pager-navigation.component.tsx (hunk 1 above)
Comment (tomdavies73) [reply src/components/pager/__internal__/pager-navigation.component.tsx:49]: This applies to the suggested changes in the `Pager` component too

Comment (tomdavies73) [reply src/components/pager/__internal__/pager-navigation.component.tsx:49]: Is there any particular reason why this change is needed? We'd be happy to discuss alternative solutions or consider it, if you feel its needed

File: cypress/components/flat-table/flat-table.cy.tsx (hunk 3 above)
Comment (MarcServat) [reply cypress/components/flat-table/flat-table.cy.tsx:2543]: thanks for the advice. I'll make the necessary changes if the refactor is merged first.

File: src/components/pager/__internal__/pager-navigation.component.tsx (hunk 1 above)
Comment (MarcServat) [reply src/components/pager/__internal__/pager-navigation.component.tsx:49]: the reason for that change, if I'm not mistaken, is because the callback is called with the wrong arguments order. In the documentation (storybook, Pager interface, PagerNavigation interface) is:  `pageSize: number, currentPage: number, origin: string`
when in the code the `onPagination` callback is called with `(currentPage, pageSize, origin) => {}`, for instance [here](https://github.com/Sage/carbon/blob/master/src/components/pager/__internal__/pager-navigation.component.tsx#L101). Instead of changing the order of the arguments in the callback I thought changing the documentation will be less painful. Please let me know if i missed anything or anything is incorrect.

Comment (tomdavies73) [reply src/components/pager/__internal__/pager-navigation.component.tsx:49]: @MarcServat thanks for pointing this out, I can see internally within `handlePageInputChange`  we are calling `onPagination` with the args in the manner you've described. I'll wait for a second reviewer to get their opinion on this, as I agree it would be good to document the args as they're actually used.

Comment (DipperTheDan) [reply src/components/pager/__internal__/pager-navigation.component.tsx:49]: I agree with the change @MarcServat has made here. This is an `internal` component too so we can make changes without it being classed as officially breaking. [RFC for internal stuff is here if you want to have a read on it](https://github.com/Sage/carbon/blob/master/rfcs/text/internal-interfaces.md)

File: src/components/pager/pager.component.tsx [hunk 4]
```diff
@@ -20,7 +20,7 @@ type PageSizeOption = {
 
 export interface PagerProps {
   /** Function called when pager changes (PageSize, Current Page) */
```
Comment (DipperTheDan) [inline src/components/pager/pager.component.tsx:22]: **suggestion:** You will also need to update this comment to reflect the changes you've made to the ordering of the parameters.

Comment (MarcServat) [reply src/components/pager/pager.component.tsx]: thanks for pointing that out. Done.

**Review by DipperTheDan — APPROVED** [review]

**Review by tomdavies73 — APPROVED** [review]
@MarcServat good work on this, and thanks for the contribution 👍

**Review by tomdavies73 — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by stephenogorman — APPROVED** [review]
