### PR TITLE
fix(focus-trap): update trap to use ref from content container FE-3795

### LINKED ISSUE #3770: Fullscreen Dialog animation is broken
### Current behaviour

The fullscreen dialog, when actioned appears on the page as a quick fade without any movement animation.

https://user-images.githubusercontent.com/2411024/109625511-4ec6c800-7b37-11eb-974e-8627896d38b4.mov

### Expected behaviour
All dialogs have a movement animation to show it appearing, in particular the fullscreen to show its not a new page.

### Suggested solution(s)

After some discussions with @edleeks87 it appears this might be related to `FocusTrap` component.

### PR DESCRIPTION
**Pull request by edleeks87**
fix #3770

### Proposed behaviour

Removes div wrapper from `FocusTrap` and replaces with fragment, now uses ref for the content container via `wrapperRef` prop

### Current behaviour

Animation does not work

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Additional context

Animation now working:

### Testing instructions

`DialogFullScreen` story to test open animation
`Dialog`, `Sidebar` and `AdvancedColorPicker` stories will need a brush over to see that focus trap still functions as before

### CODE REVIEW

**Review by bulaj — APPROVED** [review]

**Review by mkrds — DISMISSED** [review]

**Review by bulaj — DISMISSED** [review]

**Review by bulaj — APPROVED** [review]

File: src/__internal__/focus-trap/focus-trap.component.js [hunk 1]
```diff
@@ -38,16 +38,20 @@ const FocusTrap = ({
...
-
-    if (hasNewInputs(elements)) {
-      setFocusableElements(Array.from(elements));
-      setFirstElement(elements[0]);
-      setLastElement(elements[elements.length - 1]);
+    if (wrapperRef) {
+      const ref = wrapperRef.current || wrapperRef;
+
+      const elements = Array.from(
+        ref.querySelectorAll(defaultFocusableSelectors)
```
Comment (mkrds) [inline src/__internal__/focus-trap/focus-trap.component.js:45]: I don't think it's going to work if `wrapperRef` is a function (as described in propTypes)

Comment (edleeks87) [reply src/__internal__/focus-trap/focus-trap.component.js:45]: yep copy and pasted from above 🤦

**Review by mkrds — APPROVED** [review]

**Review by bulaj — APPROVED** [review]

**Review by KatarzynaQA — APPROVED** [review]

**Review by mkrds — APPROVED** [review]
