### PR TITLE
fix(select): ensure textbox placeholder can be set when passed as prop

### LINKED ISSUE #4894: The placeholder property of the Select component cannot be updated
### Current behaviour

We can no longer update the placeholder property of the Select component.

Example: https://codesandbox.io/s/select-placeholder-0vus7w?file=/src/index.js

### Expected behaviour

To be able to modify the placeholder property of the Select component.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/select-placeholder-0vus7w

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

104.26.1

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by Parsium**
fixes #4894 

### Proposed behaviour

- Remove placeholder logic in `SelectText` - let `SelectTextbox` handle this instead and just use the text that is  passed from it.
- Adjust conditionals in `SelectTextbox` that determines which placeholder text to use.
- Add and amend unit tests

https://user-images.githubusercontent.com/18368713/157647151-dd5f8ca3-2edc-4d4a-82a2-bf9976203bac.mov

### Current behaviour

- Passing a custom placeholder as a prop of `Select` does not override the default locale placeholder.

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [x] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

Added and amended unit tests have been written in a RTL style - referring to DOM elements only and not components - given future plans to migrate to RTL.

### Testing instructions

The following CodeSandbox is an example of the broken behaviour:
https://codesandbox.io/s/select-placeholder-0vus7w

And the following CodeSandbox shows the fixed behaviour:
https://codesandbox.io/s/select-placeholder-kub9e8

### CODE REVIEW

**Review by jamime — DISMISSED** [review]

File: src/components/select/__internal__/select-text/select-text.component.js [hunk 1]
```diff
@@ -57,7 +52,7 @@ const SelectText = ({
       tabIndex="-1"
       transparent={transparent}
     >
-      {formattedValue || placeholderText}
+      {formattedValue || (hasPlaceholder ? placeholder : "")}
```
Comment (edleeks87) [inline src/components/select/__internal__/select-text/select-text.component.js:55]: Could we not add a default like so `formattedValue = ""` and then change this to be like the below, that way we only check its value the one time when setting `hasPlaceholder`?

```
hasPlaceholder ? placeholder : formattedValue
```

Comment (Parsium) [reply src/components/select/__internal__/select-text/select-text.component.js:55]: Yeah this looks a lot cleaner 👍🏼

**Review by edleeks87 — APPROVED** [review]

**Review by divyajindel — APPROVED** [review]
