### PR TITLE
fix(switch): ensure inline hint text takes full width of label container

### LINKED ISSUE #7411: Problem with the width of the helpLabel in the Switch component
### Description

I am having an issue with the width of the helpLabel of the Switch component that I do not have with the Textbox component. In the case of the Switch component, the maximum width (max-width) is set to 160px, whereas this is not the case for the Textbox component.

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-bmvrtfmm?file=package.json,src%2FApp.tsx

### Steps to reproduce

Display a Swith component with a Message component in the helpLabel.

### JIRA ticket numbers (Sage only)

SBS-135745

### Suggested solution

_No response_

### Carbon version

154.13.4

### React version

v17

### Design tokens version

4.35.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Additional context

_No response_

### Confidentiality

- [x] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by nuria1110**
fix #7411

### Proposed behaviour

`labelHelp` (hint text) has no width restrictions
image

`labelWidth` can be used to set label and hint text width when `labelInline` is true:
image

When `reverse` is false, input is aligned to the right and label and hint text are aligned
image

### Current behaviour

`labelHelp` (hint text) has max-width of "160px" that cannot be changed
image
image

When `reverse` is false, input does not align to the right and label and hint text are not aligned
image
 

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

Controls have been added to `Validation` and `New Validation` test stories, container with limited width has been added to `New Validation Inline` to demonstrate text wrapping. Snapshots for these stories have been enabled.

- Check no width restrictions are set on label or hintText when label is not inline.
- When label is inline, no width should be applied by default.
- `labelWidth` prop should apply to both label and hintText, meaning both should wrap if they overflow
- `reverse` set to false should align switch to the right and hintText and label should align vertically

### CODE REVIEW

**Review by mihai-albu-sage — APPROVED** [review]

File: src/components/switch/switch.component.tsx [hunk 1]
```diff
@@ -265,18 +271,22 @@ export const Switch = React.forwardRef(
...
-            flexWrap="wrap"
             alignItems={error || warning ? "flex-start" : undefined}
             flexDirection={!reverse ? reverseDirection : direction}
             width={labelInline ? "100%" : "auto"}
           >
-            <Box data-role="label-wrapper" alignSelf={labelWrapperAlignSelf}>
+            <Box
+              data-role="label-wrapper"
+              alignSelf={labelWrapperAlignSelf}
+              width={labelInline ? labelWrapperWidth : undefined}
```
Comment (tomdavies73) [inline src/components/switch/switch.component.tsx:288]: **suggestion**:

You could do this instead: 

` {...(labelWidth && { width: `${labelWidth}%` })}`

This avoids using a ternary operator twice and having to define a const for something also used once

Comment (tomdavies73) [inline src/components/switch/switch.component.tsx]: **suggestion**:

You could do this instead: 

` {...(labelWidth && { width: `${labelWidth}%` })}`

This avoids using a ternary operator twice (here and line 274) and having to define the const one line 274 too

**Review by tomdavies73 — DISMISSED** [review]

**Review by mihai-albu-sage — DISMISSED** [review]

**Review by paulrobinson88 — APPROVED** [review]

**Review by tomdavies73 — APPROVED** [review]

**Review by mihai-albu-sage — APPROVED** [review]
