### PR TITLE
fix(simple-color-picker, advanced-color-picker): ensure blur blocking works when switching colors - FE-6707

### LINKED ISSUE #6850: [AdvancedColorPicker] - onBlur not being triggered the first time a new color is clicked
### Description

When changing the input value in AdvancedColorPicker by clicking a non-selected color, the onBlur callback should be triggered. But this does not happen the first time a change happens (it does on subsequent ones)

### Reproduction

https://stackblitz.com/edit/parsium-carbon-starter-bigb4p?file=src%2FApp.tsx

### Steps to reproduce

Open the dialog with the picker in, click a non-red color, and note that there is no output in the console.
Subsequently clicking a new color fires the console message as expected.

### JIRA ticket numbers (Sage only)

_No response_

### Suggested solution

_No response_

### Carbon version

141.0.6

### Design tokens version

4.29.0

### Relevant browsers

Chrome

### Relevant OSs

MacOS

### Additional context

Initial investigation suggests the problem is to do with the setting of `isBlurBlocked` in the `handleMouseDown` function (https://stackblitz.com/edit/parsium-carbon-starter-bigb4p?file=src%2FApp.tsx), with the value incorrectly being `true` when the call fails. I do not know why this is happening specifically the first time, or why we are even blocking blur at all.

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by DipperTheDan**
Blur should be blocked when switching between colors and fired when the component itself is blurred.

fixes #6850

### Proposed behaviour

Blur event should not be fired when switching between colours.
Add deprecation warning to `isBlurBlocked` prop.

### Current behaviour

Blur event is triggered every time a colour is changed.

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Playwright automation tests added or updated if required
- [x] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

N/A

### Testing instructions

New test story called `OnBlurExample` has been added to `AdvancedColorPickers` test stories. This example allows you to test when the `onBlur` event is fired as it will be logged in the console. 

Blur should only be fired if the component itself is blurred or the component is closed using the `X` button.

### CODE REVIEW

**Review by nineteen88 — APPROVED** [review]

File: src/components/simple-color-picker/simple-color-picker.component.tsx [hunk 1]
```diff
@@ -260,9 +260,15 @@ export const SimpleColorPicker = React.forwardRef<
...
 
-    if (!blurBlocked && onBlur) {
-      onBlur(ev);
-    }
+    setTimeout(() => {
+      const hasBlurred = !gridItemRefs?.current?.find(
+        (colorRef) => colorRef === document.activeElement
+      );
+      /* istanbul ignore else */
+      if (onBlur && hasBlurred && !blurBlocked) {
```
Comment (edleeks87) [inline src/components/simple-color-picker/simple-color-picker.component.tsx:268]: comment (non-blocking): I'm not convinced we need the `blurBlocked` flag anymore as the new find function should handle it as far as I can tell. If that's the case, maybe we should remove the internal state and add a deprecation warning for it? It doesn't seem to cause any issues leaving it in for now (I do think getting the dep warning in would be good) so happy to push this to a new ticket if preferred.

Comment (DipperTheDan) [reply src/components/simple-color-picker/simple-color-picker.component.tsx:268]: Yeah that is a good point. I did originally get rid of all the `blurBlocked` stuff (state/prop) and it worked with the amended blur handling code. I chose to add it back in otherwise it would have been a breaking change. I'll gladly put a deprecation warning on the prop and we can add it to the next bundle of breaking changes we do.

File: src/components/simple-color-picker/simple-color-picker.spec.tsx [hunk 2]
```diff
@@ -778,3 +778,35 @@ describe("SimpleColorPicker", () => {
...
+        name="test"
+        isBlurBlocked
+      />
+    );
+
+    expect(loggerSpy).toHaveBeenCalledWith(
+      "The 'isBlurBlocked' prop in SimpleColorPicker is deprecated and support will soon be removed."
+    );
+
+    expect(loggerSpy).toHaveBeenCalledTimes(1);
```
Comment (edleeks87) [inline src/components/simple-color-picker/simple-color-picker.spec.tsx:810]: comment (non-blocking): this is kind of pointless as we're only rendering one component etc but it's not a huge deal

**Review by edleeks87 — DISMISSED** [review]

**Review by nineteen88 — DISMISSED** [review]

**Review by paulrobinson88 — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by nineteen88 — APPROVED** [review]

**Review by paulrobinson88 — APPROVED** [review]
