### PR TITLE
fix(dismissible-box): remove minWidth from component - FE-4633

### LINKED ISSUE #4621: DismissibleBox - width prop is missing in d.ts file
### Current behaviour

If we import DismissibleBox component, we can not set width property as it's missing in d.ts file

### Expected behaviour

When i import DismissibleBox component, we can set width property

No CodeSandbox as it's working in codeSandbox environement

### CodeSandbox or Storybook URL

https://carbon.sage.com/storybook?path=/docs/dismissible-box

### JIRA Ticket (Sage Only)
SBS-24456

### Suggested Solution

_No response_

### Carbon Version

102.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### LINKED ISSUE #4627: Dissmissible box - minWidth setted but not wanted
### Current behaviour

If i want a little dissmissble box, i can not because we have a minWidth setted.
The 600px is related to the content displayed inside, not related to the size of the dissmissible box.

### Expected behaviour

I want to have a little dissmissible box less than 600px

### CodeSandbox or Storybook URL

https://codesandbox.io/s/little-waterfall-hh1pb?file=/src/index.js

### JIRA Ticket (Sage Only)

SBS-24456

### Suggested Solution

_No response_

### Carbon Version

102.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by DipperTheDan**
When the component was spec'd it was stated that the component should be no smaller than 600px for
readability purposes. New designs now require this component to be smaller than 600px in size

fixes #4627

width prop is missing from the typescript definition file.

fixes #4621

### Proposed behaviour

- Component can be smaller than 600px in width.
- `width` prop is present in the ts definition file.

### Current behaviour

- Component can not have a width of less 600px.
- `width` prop is missing from the ts definition file.
### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [ ] Cypress automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Additional context

N/A

### Testing instructions

CodeSandbox to test PR is [here](https://codesandbox.io/s/upbeat-cherry-p4vst)

### CODE REVIEW

File: src/components/dismissible-box/dismissible-box.d.ts [hunk 1]
```diff
@@ -12,6 +12,11 @@ export interface DismissibleBoxProps extends SpaceProps {
   onClose: React.MouseEventHandler<HTMLButtonElement>;
   /** Set the base color variant */
   variant?: "light" | "dark";
+  /** Use this prop to override the default width. Numbers from 0-1 are converted to percentage widths. Numbers greater
```
Comment (edleeks87) [inline src/components/dismissible-box/dismissible-box.d.ts:15]: As this component just spreads the `rest` onto the `StyledDismissibleBox` which is just a `Box` with some additional styling, I wonder if it would be better to just `extend BoxProps` and `Omit` the props we don't surface here instead (eg `display` and `justifyContent`)?

Comment (DipperTheDan) [reply src/components/dismissible-box/dismissible-box.d.ts:15]: I have no issues at all doing it that way, as long as it won't interfere with the up and coming TS refactor work.

Comment (samtjo) [reply src/components/dismissible-box/dismissible-box.d.ts:15]: Sound good to me ^^^ It won't interfere with the ts refactor 👍🏻

Comment (DipperTheDan) [reply src/components/dismissible-box/dismissible-box.d.ts:13]: Well seen as @samtjo has put his 🦭 of approval on it, I'll get the changes made. Cheers lads 😄

File: src/components/dismissible-box/dismissible-box.d.ts [hunk 2]
```diff
@@ -1,9 +1,8 @@
 import * as React from "react";
-import { SpaceProps } from "styled-system";
+import { BoxProps } from "components/box/box";
```
Comment (edleeks87) [inline src/components/dismissible-box/dismissible-box.d.ts:2]:
```suggestion
import { BoxProps } from "components/box";
```

**Review by edleeks87 — APPROVED** [review]

**Review by samtjo — APPROVED** [review]

**Review by divyajindel — APPROVED** [review]

**Review by divyajindel — APPROVED** [review]

**Review by nicktitchmarsh — APPROVED** [review]
