### PR TITLE
fix: ensure any auto-focused element is focused first when a child of a focus trapped component

### LINKED ISSUE #6384: FilterableSelect openOnFocus Dialog
### Current behaviour

FilterableSelect openOnFocus doesn't work in Dialog

### Expected behaviour

Filterable select list automaticly opened on Dialog opened

### CodeSandbox or Storybook URL

https://codesandbox.io/s/filterableselect-autofocus-in-dialog-forked-t5mnf8

### JIRA Ticket (Sage Only)

FRTRADS-14762

### Suggested Solution

_No response_

### Carbon Version

121.2.0

### Design Tokens Version

4.0.0

### What browsers are you seeing the problem on?

Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by edleeks87**
fix #6384

### Proposed behaviour

Ensures that when a Carbon input has the `autoFocus` prop set on it and rendered as a child of a focus trapped parent (`Dialog`, `DialogFullScreen`, `Sidebar`, `Confirm` and so on) is focused first when rendered. Also ensures that any elements with tabIndex of -1 are ignored by the tab guards, rendered as part of the FocusTrap, when selecting which element to focus next.

### Current behaviour

Children with `autoFocus` are not focused when a focus trapped parent is rendered
Elements with tabIndex -1 are not ignored by the tab guards in the FocusTrap

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [x] Unit tests added or updated if required
- [x] Playwright automation tests added or updated if required

#### QA

- [ ] Tested in CodeSandbox/storybook
- [ ] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

The following CodeSandbox is an example of the broken behaviour.
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]`.

https://codesandbox.io/s/charming-water-jvt46y?file=/src/App.js

### CODE REVIEW

File: src/__internal__/focus-trap/focus-trap-utils.ts [hunk 1]
```diff
@@ -142,9 +143,11 @@ const onTabGuardFocus = (
       index -= trapWrappers.length;
     }
     nextWrapper = trapWrappers[index];
-    allFocusableElementsInNextWrapper = nextWrapper?.current?.querySelectorAll(
-      focusableSelectors || defaultFocusableSelectors
-    );
+    allFocusableElementsInNextWrapper = Array.from(
```
Comment (nineteen88) [inline src/__internal__/focus-trap/focus-trap-utils.ts:146]: praise: a lot tidier

File: src/components/dialog/dialog.pw.tsx [hunk 2]
```diff
@@ -357,6 +358,22 @@ test.describe("Testing Dialog component properties", () => {
       page.getByText("I should not be scrolled into view")
     ).not.toBeInViewport();
   });
+
+  test("should loop focus whenwhen a Select component is passed as children and the user presses shift + tab", async ({
```
Comment (nineteen88) [inline src/components/dialog/dialog.pw.tsx:362]: suggestion: double when

```suggestion
  test("should loop focus when a Select component is passed as children and the user presses shift + tab", async ({
```

File: src/__internal__/focus-trap/focus-trap.component.tsx [hunk 3]
```diff
@@ -176,6 +160,32 @@ const FocusTrap = ({
...
+        defaultFocusableSelectors
+      ).find((el) => el.getAttribute("data-has-autofocus") === "true");
+      const candidateFirstElement =
+        focusFirstElement && "current" in focusFirstElement
+          ? focusFirstElement.current
+          : focusFirstElement;
+      const elementToFocus =
+        autoFocusedElement ||
+        (candidateFirstElement as HTMLElement | null | undefined) ||
+        wrapperRef.current;
```
[the remark this answers is not in the document]
Comment (edleeks87) [reply src/__internal__/focus-trap/focus-trap.component.tsx:175]: No worries, that was existing before my change so didn't touch it but I can't see why we need the additional types there. I think I'm going to switch the `autoFocus` and `candidateFirstElement` around here as well as I think if a user sets `candidateFirstElement` I think that should be priority

**Review by nineteen88 — APPROVED** [review]

**Review by DipperTheDan — DISMISSED** [review]

**Review by DipperTheDan — DISMISSED** [review]

**Review by nineteen88 — DISMISSED** [review]

**Review by stephenogorman — DISMISSED** [review]

**Review by stephenogorman — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]

**Review by nineteen88 — APPROVED** [review]
