### PR TITLE
fix(dialog): ensure enableBackgroundUI is passed to Modal

### LINKED ISSUE #6023: Dialog does not pass enableBackgroundUI to Modal
### Current behaviour

The Dialog component does not pass the accepted prop enableBackgroundUI to Modal to control the behaviour of the Modal underlay.

image

### Expected behaviour

Modal underlay should be controlled by enableBackgroundUI when provided to the Dialog component.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/stoic-gauss-w1nsnd

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

118.2.0

### Design Tokens Version

2.65.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What Operating System are you seeing the problem on?

MacOS, Windows

### Anything else we should know?

_No response_

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by DobroTora**
fix #6023 

adding modal props to Dialog and pass enableBackgroundUI

### Current behaviour
Screenshot 2025-01-21 at 13 06 28

### Checklist

- [x] Commits follow our style guide
- [x] Related issues linked in commit messages if required
- [ ] Screenshots are included in the PR if useful
- [ ] All themes are supported if required
- [ ] Unit tests added or updated if required
- [ ] Playwright automation tests added or updated if required
- [ ] Storybook added or updated if required
- [ ] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [ ] Typescript `d.ts` file added or updated if required
- [ ] Related docs have been updated if required

#### QA

- [ ] Tested in provided StackBlitz sandbox/Storybook
- [ ] Add new Playwright test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### CODE REVIEW

**Review by damienrobson-sage — CHANGES_REQUESTED** [review]

File: src/components/dialog/dialog.component.tsx [hunk 1]
```diff
@@ -127,6 +131,8 @@ export const Dialog = forwardRef<DialogHandle, DialogProps>(
       topModalOverride,
       closeButtonDataProps,
       restoreFocusOnClose = true,
+      modalProps = {},
+      enableBackgroundUI = false,
```
[the remark this answers is not in the document]
Comment (damienrobson-sage) [reply src/components/dialog/dialog.component.tsx]: **unresolved**: you don't need these:
```javascript
   modalProps = {},
   enableBackgroundUI = false,
```
Because `Dialog` extends `Modal`, `enableBackgroundUI` will already exist in `...rest`, and will be passed down automatically. `modalProps` is never used so you can safely remove it.

File: src/components/modal/modal.test.tsx [hunk 2]
```diff
@@ -41,7 +41,7 @@ const MockModal = ({
 };
 
 test("renders background overlay when enableBackgroundUI is false", () => {
-  render(<Modal onCancel={() => {}} open enableBackgroundUI={false} />);
```
Comment (tomdavies73) [inline src/components/modal/modal.test.tsx:44]: **issue**: this doesn't need to be changed

File: src/components/popover-container/popover-container-test.stories.tsx [hunk 3]
```diff
@@ -63,6 +63,7 @@ Default.story = {
     title: "Title",
     open: true,
     closeButtonDataProps: {},
+    enableBackgroundUI: false,
```
Comment (tomdavies73) [inline src/components/popover-container/popover-container-test.stories.tsx:66]: **issue**: this doesn't need to be passed here

**Review by tomdavies73 — CHANGES_REQUESTED** [review]
I think we're almost there, the spreading rest approach does work, and `enableBackgroundUI` will be passed down to the modal component. I'd just have a look at my other comments, as we can probably remove changes in 5 files total, and keep the changes limited to dialog.

I think adding some sort of test to verify the prop works, and create a baseline for the changes made would be beneficial. In `Sidebar.pw` we do this:

` [true, false].forEach((enableBackgroundUIValue) => {
    test(`verify visibility of backgroundUILocatorElement when enableBackgroundUI prop is set to ${enableBackgroundUIValue}`, async ({
      mount,
      page,
    }) => {
      await mount(
        <SidebarComponent enableBackgroundUI={enableBackgroundUIValue} />,
      );

      const backgroundUILocatorElement = backgroundUILocator(page);

      if (enableBackgroundUIValue) {
        await expect(backgroundUILocatorElement).not.toBeVisible();
      } else {
        await expect(backgroundUILocatorElement).toBeVisible();
      }
    });
  });`

File: src/components/dialog/dialog.pw.tsx [hunk 4]
```diff
@@ -29,10 +29,32 @@ import {
...
 import { CHARACTERS, SIZE } from "../../../playwright/support/constants";
-import { getDataElementByValue } from "../../../playwright/components";
+import {
+  getDataElementByValue,
+  backgroundUILocator,
+} from "../../../playwright/components";
 
 const specialCharacters = [CHARACTERS.DIACRITICS, CHARACTERS.SPECIALCHARACTERS];
 
+[true, false].forEach((enableBackgroundUIValue) => {
```
Comment (tomdavies73) [inline src/components/dialog/dialog.pw.tsx:39]: **suggestion**: this should be placed just below line 58 so it's grouped together with the other tests, which are also testing Dialog component properties

**Review by tomdavies73 — COMMENTED** [review]
Good stuff @DobroTora,

Happy to approve when the tests are moved into the correct describe block 👍

**Review by tomdavies73 — APPROVED** [review]

**Review by damienrobson-sage — DISMISSED** [review]

**Review by stephenogorman — DISMISSED** [review]

**Review by tomdavies73 — APPROVED** [review]

**Review by stephenogorman — APPROVED** [review]
