### PR TITLE
fix(accordion): resize accordion when children resize - FE-4156

### LINKED ISSUE #4143: Accordion component does not resize when children re-render
### Current behaviour
If the child of an accordion has its size changed, then the accordion does not resize to allow this to display correctly. This can be worked around by opening and closing the accordion. 

Screenshot 2021-06-09 at 16 13 32

Screenshot 2021-06-09 at 16 14 05

### Expected behaviour
The accordion should resize itself automatically based on its content

### Reproducible example
https://codesandbox.io/s/confident-aryabhata-2lfon?file=/src/index.js

Open the accordion -> change the shown items number -> close then open the accordion again

### Suggested solution(s)
Accordion should re-render when its children change size

### PR DESCRIPTION
**Pull request by mkrds**
### Proposed behaviour
Fixes an issue where Accordion did not resize when it's children resized.
fixes #4143 

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Testing instructions

https://codesandbox.io/s/cranky-bird-e127x

### CODE REVIEW

File: src/components/accordion/accordion.component.js [hunk 1]
```diff
@@ -68,16 +62,23 @@ const Accordion = React.forwardRef(
...
+        }
+      })
+    );
 
-      const event = "resize";
-      window.addEventListener(event, resizedContentHeight);
+    useEffect(() => {
+      const observerRef = observer.current;
+      const referenceRef = accordionContent.current;
+      observer.current.observe(referenceRef);
```
Comment (sjohnson-sage) [inline src/components/accordion/accordion.component.js:77]:
```suggestion
      observerRef.observe(referenceRef);
```

**Review by ianforster-sage — APPROVED** [review]

**Review by sjohnson-sage — APPROVED** [review]

**Review by sjohnson-sage — APPROVED** [review]

**Review by ZhuoyuJin — APPROVED** [review]
