### PR TITLE
fix(filterable-select): check event has a data element attribute before checking the value FE-3802

### LINKED ISSUE #3754: [FilterableSelect] Error thrown on mouse down
### Current behaviour
When clicking on the select component it intermittently throws an error.

### Expected behaviour
It should not throw an error

### Reproducible example
https://codesandbox.io/s/cocky-napier-jmfe6?file=/src/index.js

### Suggested solution(s)
The component does not check for the existence of the `data-element` attribute on the target element before inspecting its value.
See here: https://github.com/Sage/carbon/blob/c18255b6b8c62681bbf717eab9871968bef35af6/src/components/select/filterable-select/filterable-select.component.js#L389

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 66.11.1
| react-scripts    | 3.4.4
| React            | 16.8.3
| Browser          | Chrome
| npm              | 6.14.4
| Operating System | MacOS

### PR DESCRIPTION
**Pull request by edleeks87**
fix #3754

### Proposed behaviour

Adds a guard to check that `event.target.attributes["data-element"]` is not undefined before
checking if the value is `"input"`

### Current behaviour

Throws `Uncaught TypeError: Cannot read property 'value' of undefined` when input icon is clicked

### Checklist

- [x] Commits follow our style guide
- [x] Screenshots are included in the PR if useful
- [x] All themes are supported if required
- [x] Unit tests added or updated if required
- [x] Cypress automation tests added or updated if required
- [x] Storybook added or updated if required
- [x] Typescript `d.ts` file added or updated if required
- [x] Carbon implementation and Design System documentation are congruent

### Testing instructions

`design-system-select-filterable--default-story` click input icon when list is open, no error should be thrown

### CODE REVIEW

File: src/components/select/filterable-select/filterable-select.component.js [hunk 1]
```diff
@@ -388,7 +388,10 @@ const FilterableSelect = React.forwardRef(
     function handleTextboxMouseDown(event) {
       isMouseDownReported.current = true;
 
-      if (event.target.attributes["data-element"].value === "input") {
+      if (
+        event.target.attributes["data-element"] &&
+        event.target.attributes["data-element"].value === "input"
```
Comment (mkrds) [inline src/components/select/filterable-select/filterable-select.component.js:393]: FYI, this could be `event.target.attributes["data-element"]?.value`

**Review by mkrds — APPROVED** [review]

File: src/components/select/filterable-select/filterable-select.component.js (hunk 1 above)
Comment (edleeks87) [reply src/components/select/filterable-select/filterable-select.component.js:393]: Ah good point for some reason I thought optional chaining didn't work

**Review by dawidzarzycki — APPROVED** [review]

**Review by KatarzynaQA — APPROVED** [review]

**Review by DipperTheDan — APPROVED** [review]
