### PR TITLE
fix(split-button, multi-action-button): remove children iteration

### LINKED ISSUE #4784: Unable to select options from SplitButton with keyboard if children are link buttons
### Current behaviour

On Sage 200 some of our SplitButtons contain children which are links. For this we make carbon buttons into links following the example given in the [usage with routing](https://carbon.sage.com/?path=/docs/documentation-usage-with-routing--page) documentation.

When a user tries to use the keyboard to select an option from the split button, they are unable to. In the console we see `Uncaught TypeError: additionalButtons.current[nextIndex].focus is not a function` from within the Carbon SplitButton component.

Impacts accessibility and slows down our power users who like to use the keyboard.

### Expected behaviour

User should be able to select options from the dropdown with their keyboard as when the split button has only buttons as children.

### CodeSandbox or Storybook URL

https://codesandbox.io/s/bold-sunset-ztpoc?file=/src/index.js

### JIRA Ticket (Sage Only)

_No response_

### Suggested Solution

_No response_

### Carbon Version

104.0.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What Operating System are you seeing the problem on?

Windows

### Anything else we should know?

Also applies to the MultiActionButton

### Confidentiality

- [X] I confirm there is no confidential or commercially sensitive information included.

### PR DESCRIPTION
**Pull request by robinzigmond**
SplitButton and MultiActionButton used to clone their children and pass particular props, including refs - assuming each child was a Button component. This meant that the components failed to work properly when using custom child components that wrap one or more Carbon Buttons (at least unless forwardRef was used). This has now been replaced by a context-based approach using DOM selectors to achieve the same functionality no matter how the children are composed.

fix #4784

### Proposed behaviour

All functionality in SplitButton and MultiActionButton should work when consumers wrap Carbon Button in a custom child component

### Current behaviour

There are warnings in the console when using such a wrapper, and keyboard navigation fails to work

### Checklist

- [X] Commits follow our style guide
- [X] Related issues linked in commit messages if required
- [X] Screenshots are included in the PR if useful
- [X] All themes are supported if required
- [X] Unit tests added or updated if required
- [X] Cypress automation tests added or updated if required
- [X] Storybook added or updated if required
- [X] Translations added or updated (including creating or amending translation keys table in storybook) if required
- [X] Typescript `d.ts` file added or updated if required
- [X] Related docs have been updated if required

#### QA

- [x] Tested in CodeSandbox/storybook
- [x] Add new Cypress test coverage if required
- [ ] Carbon implementation matches Design System/designs
- [ ] UI Tests GitHub check reviewed if required

### Testing instructions

Ensure that the original issue is fixed, and perform regression testing on the SplitButton and MultiActionButton components.

### CODE REVIEW

File: src/components/button/button.component.tsx [hunk 1]
```diff
@@ -9,6 +9,7 @@ import { TooltipProvider } from "../../__internal__/tooltip-provider";
 import Logger from "../../__internal__/utils/logger";
 import { TooltipPositions } from "../tooltip/tooltip.config";
 import { ButtonBarContext } from "../button-bar/button-bar.component";
+import splitButtonContext from "../split-button/split-button.context";
```
Comment (edleeks87) [inline src/components/button/button.component.tsx:12]: **nitpick**: `splitButtonContext` -> `SplitButtonContext`

File: src/components/split-button/split-button.context.ts
Comment (edleeks87) [inline src/components/split-button/split-button.context.ts:1]: **comment**: I realise we're pretty inconsistent about this (as usual 🤦 ) but I think we should make this an internal file as we don't ever intend consumers to use it etc

File: src/components/button/button.component.tsx [hunk 2]
```diff
@@ -237,6 +239,10 @@ const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
 
     const [internalRef, setInternalRef] = useState<HTMLButtonElement>();
 
+    const { inSplitButton, onChildButtonClick } = useContext(
```
Comment (edleeks87) [inline src/components/button/button.component.tsx:242]: **comment**(non-blocking): I wonder if we need `inSplitButton` here at all. As `onChildButtonClick` is optional we could derive `inSplitButton` from it like so `const inSplitButton = !!onChildButtonClick;`.

File: src/components/multi-action-button/multi-action-button.component.tsx [hunk 3]
```diff
@@ -41,17 +42,21 @@ export const MultiActionButton = ({
...
-  const buttonContainer = useRef<HTMLDivElement>(null);
-  const buttonChildren = useMemo(() => React.Children.toArray(children), [
-    children,
-  ]);
-  const buttonChildrenRefs = useMemo(
-    () => buttonChildren.map(() => React.createRef<HTMLButtonElement>()),
-    [buttonChildren]
+  const childrenContainer = useRef<HTMLDivElement>(null);
+
+  const getButtonChildren = useCallback(
```
Comment (edleeks87) [inline src/components/multi-action-button/multi-action-button.component.tsx:47]: **question**: as we're doing the same thing in both Multi and Split components, I wonder if it would be worth moving this into a custom hook or a provider component? This is non-blocking for me as it may be more complicated than to integrate it with `useMenuKeyboardNavigation` being used here as well but figured I'd ask anyway 😄

File: src/components/button/button.component.tsx (hunk 1 above)
Comment (robinzigmond) [reply src/components/button/button.component.tsx:12]: Oh yeah, I was thinking uppercase was only for components but not sure why I didn't think to check other contexts that we define and use in Carbon 🤦

File: src/components/split-button/split-button.context.ts
Comment (robinzigmond) [reply src/components/split-button/split-button.context.ts:1]: I don't object, but I thought the convention was that anything not exported from the `index.ts` (which this isn't) was considered internal and use-at-your-own-risk anyway. But sure we have `__internal__` subfolders in other components - happy to put this in one of those if it makes things clearer.

File: src/components/button/button.component.tsx (hunk 2 above)
Comment (robinzigmond) [reply src/components/button/button.component.tsx:242]: It's a fair comment. I like having the explicit boolean here rather than assume the presence of another property implies anything - as what if we later we want to make `onChildButtonClick` optional even in the SplitButton case. As ever I'm probably worrying about something that will never happen 😂 - but I don't see much harm in being explicit. Happy to be persuaded otherwise though.

File: src/components/multi-action-button/multi-action-button.component.tsx (hunk 3 above)
Comment (robinzigmond) [reply src/components/multi-action-button/multi-action-button.component.tsx:47]: Fair comment. I did realise there was a lot of duplication between the two components but realised a lot of it already existed so didn't really explore further - but now you mention it I agree it's worth exploring whether some of this duplication can be put into a custom hook 👍

File: src/components/button/button.component.tsx (hunk 2 above)
Comment (edleeks87) [reply src/components/button/button.component.tsx:242]: Happy to let the second reviewer split the difference 😄

**Review by edleeks87 — APPROVED** [review]

File: src/components/button/button.component.tsx (hunk 2 above)
Comment (DipperTheDan) [reply src/components/button/button.component.tsx:242]: Personally, I prefer `const inSplitButton = !!onChildButtonClick;` approach for this particular need. As we don't have any future plans plans to change `onChildButtonClick` and if we did, we could always implement what you have here but seeing as @edleeks87 has already approved the PR, I'm not going to block the PR/request changes over it. Just my preference and not a hill I want to die on 😆

Comment (DipperTheDan) [reply src/components/button/button.component.tsx:242]: Personally, I prefer `const inSplitButton = !!onChildButtonClick;` approach for this particular need. As we don't have any future plans plans to change `onChildButtonClick` and if we did, we could always implement what you have here but seeing as @edleeks87 has already approved the PR, I'm not going to block the PR/request changes over it. Just my preference and not a hill I want to die on 😆

**Review by DipperTheDan — APPROVED** [review]

**Review by edleeks87 — APPROVED** [review]

**Review by divyajindel — APPROVED** [review]
